// Copyright Epic Games, Inc. All Rights Reserved.

#include "Flashback/FlashbackWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Castle.h"
#include "Components/AudioComponent.h"
#include "Components/Image.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/TextBlock.h"
#include "Engine/Texture2D.h"
#include "Flashback/FlashbackDefinition.h"
#include "Flashback/FlashbackSequencer.h"
#include "GameFramework/PlayerController.h"
#include "Kismet/GameplayStatics.h"
#include "Sound/SoundBase.h"

TSharedRef<SWidget> UFlashbackWidget::RebuildWidget()
{
	// The flashback widget Blueprint is generated by a script and has no designer layout, so build
	// the three driven widgets here when the designer did not supply them.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("FlashbackRoot"));
		WidgetTree->RootWidget = Root;

		auto AddFullScreen = [Root](UWidget* Child)
		{
			if (UOverlaySlot* Slot = Cast<UOverlaySlot>(Root->AddChild(Child)))
			{
				Slot->SetHorizontalAlignment(HAlign_Fill);
				Slot->SetVerticalAlignment(VAlign_Fill);
			}
		};

		if (!SlideImageA)
		{
			SlideImageA = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("SlideImageA"));
		}
		AddFullScreen(SlideImageA);

		if (!SlideImageB)
		{
			SlideImageB = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("SlideImageB"));
		}
		AddFullScreen(SlideImageB);

		if (!CaptionText)
		{
			CaptionText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("CaptionText"));
		}
		if (UOverlaySlot* CaptionSlot = Cast<UOverlaySlot>(Root->AddChild(CaptionText)))
		{
			CaptionSlot->SetHorizontalAlignment(HAlign_Center);
			CaptionSlot->SetVerticalAlignment(VAlign_Bottom);
			CaptionSlot->SetPadding(FMargin(48.f));
		}
	}

	return Super::RebuildWidget();
}

void UFlashbackWidget::NativeConstruct()
{
	Super::NativeConstruct();

	// Needed so NativeOnKeyDown receives the skip key.
	SetIsFocusable(true);

	if (SlideImageA)
	{
		SlideImageA->SetRenderOpacity(0.f);
	}
	if (SlideImageB)
	{
		SlideImageB->SetRenderOpacity(0.f);
	}
}

void UFlashbackWidget::NativeDestruct()
{
	// A world torn down mid-playback must not leave the game paused.
	if (bIsPlaying)
	{
		Finish();
	}

	Super::NativeDestruct();
}

void UFlashbackWidget::Play(UFlashbackDefinition* InFlashback)
{
	if (!Sequencer)
	{
		Sequencer = NewObject<UFlashbackSequencer>(this);
	}

	Sequencer->Initialize(InFlashback);

	if (Sequencer->IsFinished())
	{
		UE_LOG(LogCastle, Warning, TEXT("%s: Play called with an empty flashback."), *GetNameSafe(this));
		OnFlashbackFinished.Broadcast(InFlashback);
		return;
	}

	Flashback = InFlashback;
	bIsPlaying = true;
	CurrentSlideIndex = INDEX_NONE;

	if (!IsInViewport())
	{
		AddToViewport(100);
	}

	bWasPausedBeforePlay = UGameplayStatics::IsGamePaused(this);
	ApplyPlaybackInputMode(true);
	UGameplayStatics::SetGamePaused(this, true);

	if (USoundBase* Ambient = Flashback->AmbientLoop.LoadSynchronous())
	{
		AmbientAudio = PlaySound2DDuringPause(Ambient, /*bLooping=*/true);
	}

	ShowSlide(0);
	ApplyBlend(0.f);
}

void UFlashbackWidget::ShowSlide(int32 SlideIndex)
{
	if (!Flashback || !Flashback->Slides.IsValidIndex(SlideIndex))
	{
		return;
	}

	CurrentSlideIndex = SlideIndex;

	const FFlashbackSlide& Slide = Flashback->Slides[SlideIndex];

	if (SlideImageA)
	{
		if (UTexture2D* Texture = Slide.Image.LoadSynchronous())
		{
			SlideImageA->SetBrushFromTexture(Texture, /*bMatchSize=*/false);
		}
	}

	// Layer B holds the next slide and fades up across this slide's crossfade. On the last slide
	// there is nothing to fade to, so it stays blank and the crossfade reads as a fade to black.
	if (SlideImageB)
	{
		const int32 NextIndex = SlideIndex + 1;
		if (Flashback->Slides.IsValidIndex(NextIndex))
		{
			if (UTexture2D* NextTexture = Flashback->Slides[NextIndex].Image.LoadSynchronous())
			{
				SlideImageB->SetBrushFromTexture(NextTexture, /*bMatchSize=*/false);
			}
		}
		else
		{
			SlideImageB->SetBrushFromTexture(nullptr, /*bMatchSize=*/false);
		}
	}

	if (CaptionText)
	{
		CaptionText->SetText(Slide.Caption);
	}

	if (USoundBase* VoiceLine = Slide.VoiceLine.LoadSynchronous())
	{
		if (VoiceAudio)
		{
			VoiceAudio->Stop();
		}
		VoiceAudio = PlaySound2DDuringPause(VoiceLine, /*bLooping=*/false);
	}

	OnSlideStarted(SlideIndex);
}

void UFlashbackWidget::ApplyBlend(float Alpha)
{
	if (SlideImageA)
	{
		SlideImageA->SetRenderOpacity(1.f - Alpha);
	}
	if (SlideImageB)
	{
		SlideImageB->SetRenderOpacity(Alpha);
	}
}

void UFlashbackWidget::NativeTick(const FGeometry& MyGeometry, float InDeltaTime)
{
	Super::NativeTick(MyGeometry, InDeltaTime);

	if (!bIsPlaying || !Flashback || !Sequencer)
	{
		return;
	}

	const bool bFinished = Sequencer->Advance(InDeltaTime);

	if (!bFinished)
	{
		if (Sequencer->GetCurrentSlideIndex() != CurrentSlideIndex)
		{
			ShowSlide(Sequencer->GetCurrentSlideIndex());
		}
		ApplyBlend(Sequencer->GetBlendAlpha());
		return;
	}

	Finish();
}

void UFlashbackWidget::Skip()
{
	if (!bIsPlaying || !Flashback || !Flashback->bSkippable || !Sequencer)
	{
		return;
	}

	if (Sequencer->TrySkip())
	{
		Finish();
	}
}

void UFlashbackWidget::Finish()
{
	if (!bIsPlaying)
	{
		return;
	}

	bIsPlaying = false;

	if (AmbientAudio)
	{
		AmbientAudio->Stop();
		AmbientAudio = nullptr;
	}
	if (VoiceAudio)
	{
		VoiceAudio->Stop();
		VoiceAudio = nullptr;
	}

	if (!bWasPausedBeforePlay)
	{
		UGameplayStatics::SetGamePaused(this, false);
	}
	ApplyPlaybackInputMode(false);

	UFlashbackDefinition* FinishedFlashback = Flashback;
	Flashback = nullptr;
	CurrentSlideIndex = INDEX_NONE;

	RemoveFromParent();

	OnFlashbackFinished.Broadcast(FinishedFlashback);
}

FReply UFlashbackWidget::NativeOnKeyDown(const FGeometry& InGeometry, const FKeyEvent& InKeyEvent)
{
	if (bIsPlaying && Flashback && Flashback->bSkippable)
	{
		Skip();
		return FReply::Handled();
	}

	return Super::NativeOnKeyDown(InGeometry, InKeyEvent);
}

FReply UFlashbackWidget::NativeOnMouseButtonDown(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
	if (bIsPlaying && Flashback && Flashback->bSkippable)
	{
		Skip();
		return FReply::Handled();
	}

	return Super::NativeOnMouseButtonDown(InGeometry, InMouseEvent);
}

void UFlashbackWidget::ApplyPlaybackInputMode(bool bEnable)
{
	APlayerController* PC = GetOwningPlayer();
	if (!PC)
	{
		return;
	}

	if (bEnable)
	{
		bRestoreCursor = PC->bShowMouseCursor;
		PC->bShowMouseCursor = true;

		FInputModeUIOnly InputMode;
		InputMode.SetWidgetToFocus(TakeWidget());
		InputMode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);
		PC->SetInputMode(InputMode);

		SetKeyboardFocus();
	}
	else
	{
		PC->bShowMouseCursor = bRestoreCursor;
		PC->SetInputMode(FInputModeGameOnly());
	}
}

UAudioComponent* UFlashbackWidget::PlaySound2DDuringPause(USoundBase* Sound, bool bLooping)
{
	if (!Sound)
	{
		return nullptr;
	}

	// CreateSound2D does not auto-play, which lets us flag the component as a UI sound first so it
	// keeps playing while the game is paused.
	UAudioComponent* AudioComponent = UGameplayStatics::CreateSound2D(
		this, Sound, 1.f, 1.f, 0.f, nullptr, /*bPersistAcrossLevelTransition=*/false, /*bAutoDestroy=*/false);

	if (AudioComponent)
	{
		AudioComponent->bIsUISound = true;
		AudioComponent->bAutoDestroy = !bLooping;
		AudioComponent->Play();
	}

	return AudioComponent;
}
