// Copyright Epic Games, Inc. All Rights Reserved.

#include "UI/CastleSettingsWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Brushes/SlateColorBrush.h"
#include "Components/Border.h"
#include "Components/Button.h"
#include "Components/ButtonSlot.h"
#include "Components/HorizontalBox.h"
#include "Components/HorizontalBoxSlot.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/SizeBox.h"
#include "Components/SizeBoxSlot.h"
#include "Components/Slider.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "Settings/CastleSettingsSubsystem.h"

namespace CastleSettingsWidgetLayout
{
	/** Step is 0.01, so the number under the slider never shows a third decimal. */
	static constexpr float SliderStep = 0.01f;

	static constexpr float RowWidth = 760.f;
	static constexpr float LabelWidth = 300.f;
	static constexpr float ValueWidth = 90.f;
	static constexpr float SliderHeight = 28.f;

	/** Grows a text block's default font without needing a font asset of our own. */
	static void SetFontSize(UTextBlock* Text, int32 Size)
	{
		if (!Text)
		{
			return;
		}
		FSlateFontInfo Font = Text->GetFont();
		Font.Size = Size;
		Text->SetFont(Font);
	}
}

void UCastleSettingsWidget::ApplyDefaultLabels()
{
	if (TitleLabel.IsEmpty())
	{
		TitleLabel = NSLOCTEXT("Castle", "SettingsTitle", "Settings");
	}
	if (SensitivityLabel.IsEmpty())
	{
		SensitivityLabel = NSLOCTEXT("Castle", "SettingsSensitivity", "Mouse sensitivity");
	}
	if (BackLabel.IsEmpty())
	{
		BackLabel = NSLOCTEXT("Castle", "SettingsBack", "Back");
	}
}

TSharedRef<SWidget> UCastleSettingsWidget::RebuildWidget()
{
	using namespace CastleSettingsWidgetLayout;

	// WBP_Settings is generated by a script and has no designer layout, so build one here.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		ApplyDefaultLabels();

		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("SettingsRoot"));
		WidgetTree->RootWidget = Root;

		// Darker than the pause menu's dimmer: the settings screen replaces it rather than
		// sitting on top, so the frozen game should read as further away still.
		//
		// The brush is set explicitly because UBorder's default Background is an Image brush with
		// no resource, which draws nothing however it is tinted - so SetBrushColor alone leaves the
		// live game at full brightness behind the text.
		UBorder* Dimmer = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("Dimmer"));
		Dimmer->SetBrush(FSlateColorBrush(FLinearColor::White));
		Dimmer->SetBrushColor(FLinearColor(0.f, 0.f, 0.f, 0.75f));
		if (UOverlaySlot* DimmerSlot = Cast<UOverlaySlot>(Root->AddChild(Dimmer)))
		{
			DimmerSlot->SetHorizontalAlignment(HAlign_Fill);
			DimmerSlot->SetVerticalAlignment(VAlign_Fill);
		}

		OptionStack = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("OptionStack"));
		if (UOverlaySlot* StackSlot = Cast<UOverlaySlot>(Root->AddChild(OptionStack)))
		{
			StackSlot->SetHorizontalAlignment(HAlign_Center);
			StackSlot->SetVerticalAlignment(VAlign_Center);
		}

		if (!TitleText)
		{
			TitleText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("TitleText"));
		}
		TitleText->SetText(TitleLabel);
		SetFontSize(TitleText, 36);
		if (UVerticalBoxSlot* TitleSlot = Cast<UVerticalBoxSlot>(OptionStack->AddChild(TitleText)))
		{
			TitleSlot->SetHorizontalAlignment(HAlign_Center);
			TitleSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 40.f));
		}

		// --- The one option: label, slider, value, on a single fixed-width row ---------------
		USizeBox* RowBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("SensitivityRowBox"));
		RowBox->SetWidthOverride(RowWidth);
		if (UVerticalBoxSlot* RowSlot = Cast<UVerticalBoxSlot>(OptionStack->AddChild(RowBox)))
		{
			RowSlot->SetHorizontalAlignment(HAlign_Center);
			RowSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 40.f));
		}

		UHorizontalBox* Row =
			WidgetTree->ConstructWidget<UHorizontalBox>(UHorizontalBox::StaticClass(), TEXT("SensitivityRow"));
		if (USizeBoxSlot* RowInner = Cast<USizeBoxSlot>(RowBox->AddChild(Row)))
		{
			RowInner->SetHorizontalAlignment(HAlign_Fill);
			RowInner->SetVerticalAlignment(VAlign_Center);
		}

		if (!SensitivityLabelText)
		{
			SensitivityLabelText =
				WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("SensitivityLabelText"));
		}
		SensitivityLabelText->SetText(SensitivityLabel);
		SetFontSize(SensitivityLabelText, 20);

		USizeBox* LabelBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("LabelBox"));
		LabelBox->SetWidthOverride(LabelWidth);
		if (USizeBoxSlot* LabelInner = Cast<USizeBoxSlot>(LabelBox->AddChild(SensitivityLabelText)))
		{
			LabelInner->SetHorizontalAlignment(HAlign_Left);
			LabelInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* LabelSlot = Cast<UHorizontalBoxSlot>(Row->AddChild(LabelBox)))
		{
			LabelSlot->SetVerticalAlignment(VAlign_Center);
		}

		if (!SensitivitySlider)
		{
			SensitivitySlider =
				WidgetTree->ConstructWidget<USlider>(USlider::StaticClass(), TEXT("SensitivitySlider"));
		}

		USizeBox* SliderBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("SliderBox"));
		SliderBox->SetHeightOverride(SliderHeight);
		if (USizeBoxSlot* SliderInner = Cast<USizeBoxSlot>(SliderBox->AddChild(SensitivitySlider)))
		{
			SliderInner->SetHorizontalAlignment(HAlign_Fill);
			SliderInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* SliderSlot = Cast<UHorizontalBoxSlot>(Row->AddChild(SliderBox)))
		{
			SliderSlot->SetSize(FSlateChildSize(ESlateSizeRule::Fill));
			SliderSlot->SetVerticalAlignment(VAlign_Center);
			SliderSlot->SetPadding(FMargin(0.f, 0.f, 24.f, 0.f));
		}

		if (!SensitivityValueText)
		{
			SensitivityValueText =
				WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("SensitivityValueText"));
		}
		SetFontSize(SensitivityValueText, 20);

		USizeBox* ValueBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("ValueBox"));
		ValueBox->SetWidthOverride(ValueWidth);
		if (USizeBoxSlot* ValueInner = Cast<USizeBoxSlot>(ValueBox->AddChild(SensitivityValueText)))
		{
			ValueInner->SetHorizontalAlignment(HAlign_Right);
			ValueInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* ValueSlot = Cast<UHorizontalBoxSlot>(Row->AddChild(ValueBox)))
		{
			ValueSlot->SetVerticalAlignment(VAlign_Center);
		}

		// --- Back -----------------------------------------------------------------------------
		if (!BackButton)
		{
			BackButton = WidgetTree->ConstructWidget<UButton>(UButton::StaticClass(), TEXT("BackButton"));
		}

		UTextBlock* BackText =
			WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("BackButtonLabel"));
		BackText->SetText(BackLabel);
		SetFontSize(BackText, 20);
		if (UButtonSlot* BackTextSlot = Cast<UButtonSlot>(BackButton->AddChild(BackText)))
		{
			BackTextSlot->SetHorizontalAlignment(HAlign_Center);
			BackTextSlot->SetPadding(FMargin(48.f, 12.f));
		}
		if (UVerticalBoxSlot* BackSlot = Cast<UVerticalBoxSlot>(OptionStack->AddChild(BackButton)))
		{
			BackSlot->SetHorizontalAlignment(HAlign_Center);
		}
	}

	return Super::RebuildWidget();
}

void UCastleSettingsWidget::NativeConstruct()
{
	Super::NativeConstruct();

	ApplyDefaultLabels();

	if (SensitivitySlider)
	{
		// The range is the subsystem's, not the designer's: a slider that can ask for a value
		// the subsystem clamps away would snap back under the player's thumb.
		SensitivitySlider->SetMinValue(UCastleSettingsSubsystem::MinLookSensitivity);
		SensitivitySlider->SetMaxValue(UCastleSettingsSubsystem::MaxLookSensitivity);
		SensitivitySlider->SetStepSize(CastleSettingsWidgetLayout::SliderStep);
	}

	if (!bBound)
	{
		if (SensitivitySlider)
		{
			SensitivitySlider->OnValueChanged.AddDynamic(this, &UCastleSettingsWidget::HandleSensitivityChanged);
		}
		if (BackButton)
		{
			BackButton->OnClicked.AddDynamic(this, &UCastleSettingsWidget::HandleBackClicked);
		}
		bBound = true;
	}

	RefreshFromSettings();
}

void UCastleSettingsWidget::NativeDestruct()
{
	if (bBound)
	{
		if (SensitivitySlider)
		{
			SensitivitySlider->OnValueChanged.RemoveDynamic(this, &UCastleSettingsWidget::HandleSensitivityChanged);
		}
		if (BackButton)
		{
			BackButton->OnClicked.RemoveDynamic(this, &UCastleSettingsWidget::HandleBackClicked);
		}
		bBound = false;
	}

	Super::NativeDestruct();
}

void UCastleSettingsWidget::RefreshFromSettings()
{
	const UCastleSettingsSubsystem* SettingsSubsystem = UCastleSettingsSubsystem::Get(this);
	const float Sensitivity = SettingsSubsystem
		? SettingsSubsystem->GetLookSensitivity()
		: FCastleSettings().LookSensitivity;

	if (SensitivitySlider)
	{
		SensitivitySlider->SetValue(Sensitivity);
	}
	UpdateValueText(Sensitivity);
}

void UCastleSettingsWidget::UpdateValueText(float Value)
{
	if (SensitivityValueText)
	{
		SensitivityValueText->SetText(FText::FromString(FString::Printf(TEXT("%.2f"), Value)));
	}
}

void UCastleSettingsWidget::HandleSensitivityChanged(float Value)
{
	if (UCastleSettingsSubsystem* SettingsSubsystem = UCastleSettingsSubsystem::Get(this))
	{
		SettingsSubsystem->SetLookSensitivity(Value);
		UpdateValueText(SettingsSubsystem->GetLookSensitivity());
		return;
	}

	UpdateValueText(UCastleSettingsSubsystem::ClampLookSensitivity(Value));
}

void UCastleSettingsWidget::HandleBackClicked()
{
	OnBackRequested.Broadcast();
}
