// Copyright Epic Games, Inc. All Rights Reserved.

#include "UI/CastlePauseWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Components/Border.h"
#include "Components/Button.h"
#include "Components/ButtonSlot.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"

void UCastlePauseWidget::ApplyDefaultLabels()
{
	if (TitleLabel.IsEmpty())
	{
		TitleLabel = NSLOCTEXT("Castle", "PauseTitle", "Paused");
	}
	if (ResumeLabel.IsEmpty())
	{
		ResumeLabel = NSLOCTEXT("Castle", "PauseResume", "Resume");
	}
	if (RestartMissionLabel.IsEmpty())
	{
		RestartMissionLabel = NSLOCTEXT("Castle", "PauseRestart", "Restart mission");
	}
	if (QuitToDesktopLabel.IsEmpty())
	{
		QuitToDesktopLabel = NSLOCTEXT("Castle", "PauseQuit", "Quit to desktop");
	}
}

TSharedRef<SWidget> UCastlePauseWidget::RebuildWidget()
{
	// WBP_Pause is generated by a script and has no designer layout, so build one here.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		ApplyDefaultLabels();

		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("PauseRoot"));
		WidgetTree->RootWidget = Root;

		// A dimmer so the frozen game reads as background rather than as the menu.
		UBorder* Dimmer = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("Dimmer"));
		Dimmer->SetBrushColor(FLinearColor(0.f, 0.f, 0.f, 0.6f));
		if (UOverlaySlot* DimmerSlot = Cast<UOverlaySlot>(Root->AddChild(Dimmer)))
		{
			DimmerSlot->SetHorizontalAlignment(HAlign_Fill);
			DimmerSlot->SetVerticalAlignment(VAlign_Fill);
		}

		ButtonStack = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("ButtonStack"));
		if (UOverlaySlot* StackSlot = Cast<UOverlaySlot>(Root->AddChild(ButtonStack)))
		{
			StackSlot->SetHorizontalAlignment(HAlign_Center);
			StackSlot->SetVerticalAlignment(VAlign_Center);
		}

		if (!TitleText)
		{
			TitleText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("TitleText"));
		}
		TitleText->SetText(TitleLabel);
		if (UVerticalBoxSlot* TitleSlot = Cast<UVerticalBoxSlot>(ButtonStack->AddChild(TitleText)))
		{
			TitleSlot->SetHorizontalAlignment(HAlign_Center);
			TitleSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 32.f));
		}

		auto AddButton = [this](TObjectPtr<UButton>& ButtonSlot, const TCHAR* Name, const FText& Label)
		{
			if (!ButtonSlot)
			{
				ButtonSlot = WidgetTree->ConstructWidget<UButton>(UButton::StaticClass(), Name);
			}

			UTextBlock* Text = WidgetTree->ConstructWidget<UTextBlock>(
				UTextBlock::StaticClass(), *(FString(Name) + TEXT("Label")));
			Text->SetText(Label);
			if (UButtonSlot* TextSlot = Cast<UButtonSlot>(ButtonSlot->AddChild(Text)))
			{
				TextSlot->SetHorizontalAlignment(HAlign_Center);
				TextSlot->SetPadding(FMargin(48.f, 12.f));
			}

			if (UVerticalBoxSlot* StackEntry = Cast<UVerticalBoxSlot>(ButtonStack->AddChild(ButtonSlot)))
			{
				StackEntry->SetHorizontalAlignment(HAlign_Fill);
				StackEntry->SetPadding(FMargin(0.f, 6.f));
			}
		};

		AddButton(ResumeButton, TEXT("ResumeButton"), ResumeLabel);
		AddButton(RestartMissionButton, TEXT("RestartMissionButton"), RestartMissionLabel);
		AddButton(QuitToDesktopButton, TEXT("QuitToDesktopButton"), QuitToDesktopLabel);
	}

	return Super::RebuildWidget();
}

void UCastlePauseWidget::NativeConstruct()
{
	Super::NativeConstruct();

	ApplyDefaultLabels();

	if (bBound)
	{
		return;
	}

	if (ResumeButton)
	{
		ResumeButton->OnClicked.AddDynamic(this, &UCastlePauseWidget::HandleResumeClicked);
	}
	if (RestartMissionButton)
	{
		RestartMissionButton->OnClicked.AddDynamic(this, &UCastlePauseWidget::HandleRestartMissionClicked);
	}
	if (QuitToDesktopButton)
	{
		QuitToDesktopButton->OnClicked.AddDynamic(this, &UCastlePauseWidget::HandleQuitToDesktopClicked);
	}

	bBound = true;
}

void UCastlePauseWidget::NativeDestruct()
{
	if (bBound)
	{
		if (ResumeButton)
		{
			ResumeButton->OnClicked.RemoveDynamic(this, &UCastlePauseWidget::HandleResumeClicked);
		}
		if (RestartMissionButton)
		{
			RestartMissionButton->OnClicked.RemoveDynamic(this, &UCastlePauseWidget::HandleRestartMissionClicked);
		}
		if (QuitToDesktopButton)
		{
			QuitToDesktopButton->OnClicked.RemoveDynamic(this, &UCastlePauseWidget::HandleQuitToDesktopClicked);
		}
		bBound = false;
	}

	Super::NativeDestruct();
}

void UCastlePauseWidget::HandleResumeClicked()
{
	OnResumeClicked.Broadcast();
}

void UCastlePauseWidget::HandleRestartMissionClicked()
{
	OnRestartMissionClicked.Broadcast();
}

void UCastlePauseWidget::HandleQuitToDesktopClicked()
{
	OnQuitToDesktopClicked.Broadcast();
}
