// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "Combat/WeaponDefinition.h"
#include "CastleHotbarWidget.generated.h"

class UBorder;
class UHorizontalBox;
class UInventoryComponent;
class UTextBlock;

/**
 * Three boxes along the bottom of the screen, one per hotbar slot: the key that selects it,
 * the weapon's short name and, for a gun, its ammo. The active slot is drawn bright, an empty
 * slot is dimmed.
 *
 * Built in C++ like the rest of the HUD, because WBP_Hotbar is generated by a script and has
 * no designer layout. UCastleHudWidget creates one and parents it into its own overlay.
 *
 * Every piece of state is a pure function of the bound inventory, so a test can bind one and
 * read the labels back without building Slate.
 */
UCLASS(Blueprintable, BlueprintType)
class CASTLE_API UCastleHotbarWidget : public UUserWidget
{
	GENERATED_BODY()

public:
	/** Binds to Inventory's change delegates and repaints. Passing null unbinds. */
	UFUNCTION(BlueprintCallable, Category = "HUD|Hotbar")
	void BindToInventory(UInventoryComponent* Inventory);

	/** Finds the owning pawn's inventory and binds to it. Called from NativeConstruct. */
	UFUNCTION(BlueprintCallable, Category = "HUD|Hotbar")
	void BindToOwningPawn();

	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	UInventoryComponent* GetBoundInventory() const { return BoundInventory; }

	/** Repaints every slot box from the bound inventory. */
	UFUNCTION(BlueprintCallable, Category = "HUD|Hotbar")
	void RefreshSlots();

	/** Active slot of the bound inventory, or Hands when nothing is bound. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	EHotbarSlot GetActiveSlot() const;

	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	bool IsSlotActive(EHotbarSlot HotbarSlot) const;

	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	bool IsSlotEmpty(EHotbarSlot HotbarSlot) const;

	/** "1", "2", "3": the key that selects the slot. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	static FText GetSlotKeyText(EHotbarSlot HotbarSlot);

	/** The weapon's short name, or an em dash for an empty slot. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	FText GetSlotNameText(EHotbarSlot HotbarSlot) const;

	/** "12 / 24" for a gun; empty for fists and for an empty slot. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	FText GetSlotAmmoText(EHotbarSlot HotbarSlot) const;

	/** The colour a slot box is drawn in right now: active, filled or dimmed empty. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	FLinearColor GetSlotColor(EHotbarSlot HotbarSlot) const;

protected:
	//~ Begin UUserWidget interface
	virtual TSharedRef<SWidget> RebuildWidget() override;
	virtual void NativeConstruct() override;
	virtual void NativeDestruct() override;
	//~ End UUserWidget interface

	UFUNCTION()
	void HandleInventoryChanged();

	UFUNCTION()
	void HandleActiveSlotChanged(EHotbarSlot OldSlot, EHotbarSlot NewSlot);

	/** Row the three slot boxes live in. Built in RebuildWidget. */
	UPROPERTY(BlueprintReadOnly, Category = "HUD|Hotbar", meta = (BindWidgetOptional))
	TObjectPtr<UHorizontalBox> SlotRow = nullptr;

	UPROPERTY(Transient, BlueprintReadOnly, Category = "HUD|Hotbar")
	TArray<TObjectPtr<UBorder>> SlotBoxes;

	UPROPERTY(Transient, BlueprintReadOnly, Category = "HUD|Hotbar")
	TArray<TObjectPtr<UTextBlock>> SlotKeyTexts;

	UPROPERTY(Transient, BlueprintReadOnly, Category = "HUD|Hotbar")
	TArray<TObjectPtr<UTextBlock>> SlotNameTexts;

	UPROPERTY(Transient, BlueprintReadOnly, Category = "HUD|Hotbar")
	TArray<TObjectPtr<UTextBlock>> SlotAmmoTexts;

	/** The slot Frank is holding: the one bright box on the bar. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "HUD|Hotbar")
	FLinearColor ActiveSlotColor = FLinearColor(0.22f, 1.f, 0.08f, 0.85f);

	/** A slot that holds something but is not in his hands. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "HUD|Hotbar")
	FLinearColor FilledSlotColor = FLinearColor(0.f, 0.f, 0.f, 0.55f);

	/** A slot with nothing in it. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "HUD|Hotbar")
	FLinearColor EmptySlotColor = FLinearColor(0.f, 0.f, 0.f, 0.25f);

	UPROPERTY(Transient)
	TObjectPtr<UInventoryComponent> BoundInventory = nullptr;
};
