// Copyright Epic Games, Inc. All Rights Reserved.

#include "UI/CastleHudWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Castle.h"
#include "Combat/TakedownComponent.h"
#include "Combat/WeaponComponent.h"
#include "Components/Image.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/TextBlock.h"
#include "GameFramework/Pawn.h"
#include "GameFramework/PlayerController.h"
#include "Mission/MissionDefinition.h"
#include "Mission/MissionObjective.h"
#include "Mission/MissionSubsystem.h"

TSharedRef<SWidget> UCastleHudWidget::RebuildWidget()
{
	// WBP_Hud is generated by a script and has no designer layout, so build the four driven
	// widgets here when nothing is bound.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("HudRoot"));
		WidgetTree->RootWidget = Root;

		auto AddText = [this, Root](TObjectPtr<UTextBlock>& TextSlot, const TCHAR* Name,
			EHorizontalAlignment HAlign, EVerticalAlignment VAlign, const FMargin& TextPadding)
		{
			if (!TextSlot)
			{
				TextSlot = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), Name);
			}
			if (UOverlaySlot* OverlaySlot = Cast<UOverlaySlot>(Root->AddChild(TextSlot)))
			{
				OverlaySlot->SetHorizontalAlignment(HAlign);
				OverlaySlot->SetVerticalAlignment(VAlign);
				OverlaySlot->SetPadding(TextPadding);
			}
		};

		AddText(ObjectiveText, TEXT("ObjectiveText"), HAlign_Left, VAlign_Top, FMargin(48.f, 48.f, 0.f, 0.f));
		AddText(AmmoText, TEXT("AmmoText"), HAlign_Right, VAlign_Bottom, FMargin(0.f, 0.f, 48.f, 48.f));
		AddText(PromptText, TEXT("PromptText"), HAlign_Center, VAlign_Center, FMargin(0.f, 120.f, 0.f, 0.f));

		if (!Crosshair)
		{
			Crosshair = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("Crosshair"));
			Crosshair->SetDesiredSizeOverride(FVector2D(4.f, 4.f));
		}
		if (UOverlaySlot* CrosshairSlot = Cast<UOverlaySlot>(Root->AddChild(Crosshair)))
		{
			CrosshairSlot->SetHorizontalAlignment(HAlign_Center);
			CrosshairSlot->SetVerticalAlignment(VAlign_Center);
		}
	}

	return Super::RebuildWidget();
}

void UCastleHudWidget::NativeConstruct()
{
	Super::NativeConstruct();

	if (MissionCompleteText.IsEmpty())
	{
		MissionCompleteText = NSLOCTEXT("Castle", "MissionComplete", "Mission complete");
	}

	BindToGame();
	RefreshObjective();
	RefreshAmmo();
	ClearPrompt();
}

void UCastleHudWidget::NativeDestruct()
{
	UnbindFromGame();

	Super::NativeDestruct();
}

void UCastleHudWidget::BindToGame()
{
	if (bBound)
	{
		return;
	}

	if (UMissionSubsystem* Missions = UMissionSubsystem::Get(this))
	{
		Missions->OnMissionStarted.AddDynamic(this, &UCastleHudWidget::HandleMissionStarted);
		Missions->OnObjectiveUpdated.AddDynamic(this, &UCastleHudWidget::HandleObjectiveUpdated);
		Missions->OnMissionComplete.AddDynamic(this, &UCastleHudWidget::HandleMissionComplete);
	}

	if (UWeaponComponent* Weapon = FindPawnWeapon())
	{
		Weapon->OnAmmoChanged.AddDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		BoundWeapon = Weapon;
	}

	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	if (UTakedownComponent* Takedown = Pawn ? Pawn->FindComponentByClass<UTakedownComponent>() : nullptr)
	{
		Takedown->OnTakedownPerformed.AddDynamic(this, &UCastleHudWidget::HandleTakedownPerformed);
	}

	bBound = true;
}

void UCastleHudWidget::UnbindFromGame()
{
	if (!bBound)
	{
		return;
	}

	if (UMissionSubsystem* Missions = UMissionSubsystem::Get(this))
	{
		Missions->OnMissionStarted.RemoveDynamic(this, &UCastleHudWidget::HandleMissionStarted);
		Missions->OnObjectiveUpdated.RemoveDynamic(this, &UCastleHudWidget::HandleObjectiveUpdated);
		Missions->OnMissionComplete.RemoveDynamic(this, &UCastleHudWidget::HandleMissionComplete);
	}

	if (BoundWeapon)
	{
		BoundWeapon->OnAmmoChanged.RemoveDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		BoundWeapon = nullptr;
	}

	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	if (UTakedownComponent* Takedown = Pawn ? Pawn->FindComponentByClass<UTakedownComponent>() : nullptr)
	{
		Takedown->OnTakedownPerformed.RemoveDynamic(this, &UCastleHudWidget::HandleTakedownPerformed);
	}

	bBound = false;
}

UWeaponComponent* UCastleHudWidget::FindPawnWeapon() const
{
	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	return Pawn ? Pawn->FindComponentByClass<UWeaponComponent>() : nullptr;
}

FText UCastleHudWidget::FormatAmmo(int32 Magazine, int32 Reserve)
{
	return FText::FromString(FString::Printf(TEXT("%d / %d"), Magazine, Reserve));
}

FText UCastleHudWidget::BuildObjectiveText() const
{
	const UMissionSubsystem* Missions = UMissionSubsystem::Get(this);
	if (!Missions)
	{
		return FText::GetEmpty();
	}

	const UMissionDefinition* Mission = Missions->GetCurrentMission();
	if (!Mission || !Mission->bShowObjectiveText)
	{
		return FText::GetEmpty();
	}

	if (const UMissionObjective* Objective = Missions->GetCurrentObjective())
	{
		return Objective->Title;
	}

	return Missions->IsMissionComplete() ? MissionCompleteText : FText::GetEmpty();
}

void UCastleHudWidget::RefreshObjective()
{
	if (ObjectiveText)
	{
		ObjectiveText->SetText(BuildObjectiveText());
	}
}

void UCastleHudWidget::RefreshAmmo()
{
	if (!AmmoText)
	{
		return;
	}

	// The pawn can gain a weapon component (or have it enabled) partway through the level.
	UWeaponComponent* Weapon = FindPawnWeapon();
	if (Weapon && Weapon != BoundWeapon)
	{
		if (BoundWeapon)
		{
			BoundWeapon->OnAmmoChanged.RemoveDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		}
		Weapon->OnAmmoChanged.AddDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		BoundWeapon = Weapon;
	}

	if (!Weapon || !Weapon->HasWeapon())
	{
		AmmoText->SetText(FText::GetEmpty());
		return;
	}

	AmmoText->SetText(FormatAmmo(Weapon->CurrentAmmo, Weapon->ReserveAmmo));
}

void UCastleHudWidget::SetPrompt(FText Prompt)
{
	CurrentPrompt = Prompt;
	if (PromptText)
	{
		PromptText->SetText(CurrentPrompt);
	}
}

void UCastleHudWidget::ClearPrompt()
{
	SetPrompt(FText::GetEmpty());
}

void UCastleHudWidget::HandleMissionStarted(UMissionDefinition* /*Mission*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleObjectiveUpdated(UMissionObjective* /*Objective*/, int32 /*ObjectiveIndex*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleMissionComplete(UMissionDefinition* /*Mission*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleAmmoChanged(int32 /*Magazine*/, int32 /*Reserve*/)
{
	RefreshAmmo();
}

void UCastleHudWidget::HandleTakedownPerformed(AActor* /*Target*/)
{
	// The guard is down; whatever prompt pointed at him is stale.
	ClearPrompt();
}
