// Copyright Epic Games, Inc. All Rights Reserved.

#include "UI/CastleHudWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Brushes/SlateColorBrush.h"
#include "Castle.h"
#include "CastlePlayerController.h"
#include "Combat/BowComponent.h"
#include "Combat/TakedownComponent.h"
#include "Combat/WeaponComponent.h"
#include "Blueprint/WidgetLayoutLibrary.h"
#include "Components/Border.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/Image.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/TextBlock.h"
#include "GameFramework/Pawn.h"
#include "GameFramework/PlayerController.h"
#include "Mission/MissionDefinition.h"
#include "Mission/MissionObjective.h"
#include "Mission/MissionSubsystem.h"
#include "Player/CastleCharacter.h"
#include "Player/GrappleComponent.h"
#include "UI/CastleHotbarWidget.h"
#include "World/GrappleAnchor.h"

TSharedRef<SWidget> UCastleHudWidget::RebuildWidget()
{
	// WBP_Hud is generated by a script and has no designer layout, so build the four driven
	// widgets here when nothing is bound.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("HudRoot"));
		WidgetTree->RootWidget = Root;

		auto AddText = [this, Root](TObjectPtr<UTextBlock>& TextSlot, const TCHAR* Name,
			EHorizontalAlignment HAlign, EVerticalAlignment VAlign, const FMargin& TextPadding)
		{
			if (!TextSlot)
			{
				TextSlot = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), Name);
			}
			if (UOverlaySlot* OverlaySlot = Cast<UOverlaySlot>(Root->AddChild(TextSlot)))
			{
				OverlaySlot->SetHorizontalAlignment(HAlign);
				OverlaySlot->SetVerticalAlignment(VAlign);
				OverlaySlot->SetPadding(TextPadding);
			}
		};

		AddText(ObjectiveText, TEXT("ObjectiveText"), HAlign_Left, VAlign_Top, FMargin(48.f, 48.f, 0.f, 0.f));
		AddText(AmmoText, TEXT("AmmoText"), HAlign_Right, VAlign_Bottom, FMargin(0.f, 0.f, 48.f, 48.f));
		AddText(PromptText, TEXT("PromptText"), HAlign_Center, VAlign_Center, FMargin(0.f, 120.f, 0.f, 0.f));
		AddText(DebugText, TEXT("DebugText"), HAlign_Left, VAlign_Top, FMargin(48.f, 80.f, 0.f, 0.f));
		DebugText->SetVisibility(ESlateVisibility::Collapsed);

		BuildReticle(Root);
		BuildGrappleMarker(Root);

		// The hotbar is its own widget so it can be styled and tested on its own, but it lives
		// inside the HUD's overlay rather than being a second thing the controller manages.
		TSubclassOf<UCastleHotbarWidget> HotbarClass = HotbarWidgetClass;
		if (!HotbarClass)
		{
			HotbarClass = UCastleHotbarWidget::StaticClass();
		}
		Hotbar = WidgetTree->ConstructWidget<UCastleHotbarWidget>(HotbarClass, TEXT("Hotbar"));
		if (UOverlaySlot* HotbarSlot = Cast<UOverlaySlot>(Root->AddChild(Hotbar)))
		{
			HotbarSlot->SetHorizontalAlignment(HAlign_Center);
			HotbarSlot->SetVerticalAlignment(VAlign_Bottom);
			HotbarSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 24.f));
		}
	}

	return Super::RebuildWidget();
}

void UCastleHudWidget::BuildReticle(UOverlay* Root)
{
	if (!WidgetTree || !Root)
	{
		return;
	}

	if (!Reticle)
	{
		Reticle = WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(), TEXT("Reticle"));
	}

	// The canvas fills the screen and the dot is anchored to its centre, which is the only way
	// to land on the exact centre pixel regardless of resolution.
	if (UOverlaySlot* ReticleSlot = Cast<UOverlaySlot>(Root->AddChild(Reticle)))
	{
		ReticleSlot->SetHorizontalAlignment(HAlign_Fill);
		ReticleSlot->SetVerticalAlignment(VAlign_Fill);
	}

	ReticleDot = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("ReticleDot"));
	ReticleDot->SetPadding(FMargin(0.f));
	if (UCanvasPanelSlot* DotSlot = Cast<UCanvasPanelSlot>(Reticle->AddChild(ReticleDot)))
	{
		DotSlot->SetAnchors(FAnchors(0.5f, 0.5f));
		DotSlot->SetAlignment(FVector2D(0.5f, 0.5f));
		DotSlot->SetAutoSize(false);
		DotSlot->SetPosition(FVector2D::ZeroVector);
	}

	// The spread ring: a transparent box with a round outline, sized every frame to the cone.
	FSlateBrush RingBrush;
	RingBrush.DrawAs = ESlateBrushDrawType::RoundedBox;
	RingBrush.TintColor = FSlateColor(FLinearColor::Transparent);
	RingBrush.OutlineSettings = FSlateBrushOutlineSettings(0.f, FSlateColor(ReticleColor), RingLineWidth);
	RingBrush.OutlineSettings.RoundingType = ESlateBrushRoundingType::HalfHeightRadius;
	ReticleRing = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("ReticleRing"));
	ReticleRing->SetBrush(RingBrush);
	if (UCanvasPanelSlot* RingSlot = Cast<UCanvasPanelSlot>(Reticle->AddChild(ReticleRing)))
	{
		RingSlot->SetAnchors(FAnchors(0.5f, 0.5f));
		RingSlot->SetAlignment(FVector2D(0.5f, 0.5f));
		RingSlot->SetAutoSize(false);
		RingSlot->SetPosition(FVector2D::ZeroVector);
	}

	// The draw bar: a dim track and a fill anchored to its left end.
	auto AddBar = [this](const TCHAR* Name, const FLinearColor& Color)
	{
		UBorder* Bar = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), Name);
		Bar->SetBrush(FSlateColorBrush(FLinearColor::White));
		Bar->SetBrushColor(Color);
		Bar->SetPadding(FMargin(0.f));
		if (UCanvasPanelSlot* BarSlot = Cast<UCanvasPanelSlot>(Reticle->AddChild(Bar)))
		{
			BarSlot->SetAnchors(FAnchors(0.5f, 0.5f));
			BarSlot->SetAlignment(FVector2D(0.f, 0.5f));
			BarSlot->SetAutoSize(false);
			BarSlot->SetPosition(FVector2D(-DrawBarWidth * 0.5f, DrawBarOffset));
			BarSlot->SetSize(FVector2D(DrawBarWidth, DrawBarHeight));
		}
		return Bar;
	};
	DrawBarBack = AddBar(TEXT("DrawBarBack"), FLinearColor(0.f, 0.f, 0.f, 0.45f));
	DrawBarFill = AddBar(TEXT("DrawBarFill"), ReticleColor);

	RefreshReticle();
	RefreshDrawIndicator();
}

float UCastleHudWidget::ComputeSpreadRingRadius(float SpreadDegrees, float FovDegrees, float ViewportWidth, float Distance)
{
	const float HalfFov = FMath::DegreesToRadians(FMath::Clamp(FovDegrees, 1.f, 170.f) * 0.5f);
	const float WorldRadius = Distance * FMath::Tan(FMath::DegreesToRadians(FMath::Max(SpreadDegrees, 0.f)));
	const float HalfWidthAtDistance = Distance * FMath::Tan(HalfFov);
	return HalfWidthAtDistance > 0.f ? WorldRadius / HalfWidthAtDistance * ViewportWidth * 0.5f : 0.f;
}

void UCastleHudWidget::SetDrawState(bool bInDrawing, float InFraction, float InRingRadius, bool bInPerfect)
{
	bDrawing = bInDrawing;
	DrawFraction = bInDrawing ? FMath::Clamp(InFraction, 0.f, 1.f) : 0.f;
	bPerfectWindow = bInDrawing && bInPerfect;
	RingRadius = bInDrawing ? FMath::Max(InRingRadius, MinRingRadius) : 0.f;
	RefreshDrawIndicator();
}

void UCastleHudWidget::RefreshDrawIndicator()
{
	const ESlateVisibility Shown = bDrawing ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed;
	const bool bFlashing = HitFlashRemaining > 0.f;
	const FLinearColor Colour = bFlashing ? HitMarkerColor : ReticleColor;
	if (ReticleRing)
	{
		// The ring is the spread while drawing, and the hit marker (a small white ring) after.
		const float Radius = bDrawing ? RingRadius : HitRingRadius;
		ReticleRing->SetVisibility(bDrawing || bFlashing ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
		FSlateBrush Brush = ReticleRing->GetBrush();
		Brush.OutlineSettings.Color = FSlateColor(Colour);
		ReticleRing->SetBrush(Brush);
		if (UCanvasPanelSlot* RingSlot = Cast<UCanvasPanelSlot>(ReticleRing->Slot))
		{
			RingSlot->SetSize(FVector2D(Radius * 2.f, Radius * 2.f));
		}
	}
	if (DrawBarBack)
	{
		DrawBarBack->SetVisibility(Shown);
	}
	if (DrawBarFill)
	{
		DrawBarFill->SetVisibility(bDrawing && DrawFraction > 0.f ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
		// Full and flashing in the perfect window: release now.
		const bool bFlashOn = bPerfectWindow && FMath::Fmod(FPlatformTime::Seconds() * 20.0, 2.0) < 1.0;
		DrawBarFill->SetBrushColor(bPerfectWindow ? (bFlashOn ? FLinearColor::White : PerfectColor) : Colour);
		if (UCanvasPanelSlot* FillSlot = Cast<UCanvasPanelSlot>(DrawBarFill->Slot))
		{
			FillSlot->SetSize(FVector2D(DrawBarWidth * DrawFraction, DrawBarHeight));
		}
	}
}

UBowComponent* UCastleHudWidget::FindPawnBow() const
{
	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	return Pawn ? Pawn->FindComponentByClass<UBowComponent>() : nullptr;
}

void UCastleHudWidget::PollPawnDrawState(const FGeometry& MyGeometry)
{
	UBowComponent* Bow = FindPawnBow();
	if (Bow != BoundBow)
	{
		if (BoundBow)
		{
			BoundBow->OnHit.RemoveDynamic(this, &UCastleHudWidget::HandleBowHit);
		}
		BoundBow = Bow;
		if (BoundBow)
		{
			BoundBow->OnHit.AddDynamic(this, &UCastleHudWidget::HandleBowHit);
		}
	}

	const APlayerController* PC = GetOwningPlayer();
	const ACastleCharacter* Character = PC ? Cast<ACastleCharacter>(PC->GetPawn()) : nullptr;
	if (!Bow || !Bow->IsDrawing() || !Character)
	{
		SetDrawState(false, 0.f, 0.f, false);
		return;
	}
	const float Radius = ComputeSpreadRingRadius(Bow->GetCurrentSpreadDegrees(), Character->GetCurrentFOV(),
		MyGeometry.GetLocalSize().X, ReticleSpreadDistance);
	SetDrawState(true, Bow->GetDrawFraction(), Radius, Bow->IsInPerfectWindow());
}

void UCastleHudWidget::HandleBowHit(AActor* /*HitActor*/, float /*Damage*/, bool /*bHeadshot*/)
{
	FlashHitMarker();
}

void UCastleHudWidget::RefreshReticle()
{
	if (ReticleDot)
	{
		ReticleDot->SetBrushColor(GetReticleColor());
		if (UCanvasPanelSlot* DotSlot = Cast<UCanvasPanelSlot>(ReticleDot->Slot))
		{
			DotSlot->SetSize(FVector2D(ReticleSizePixels, ReticleSizePixels));
		}
	}

	if (Reticle)
	{
		Reticle->SetVisibility(IsReticleVisible() ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	}
}

void UCastleHudWidget::BuildGrappleMarker(UOverlay* Root)
{
	if (!WidgetTree || !Root)
	{
		return;
	}

	GrappleCanvas = WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(), TEXT("GrappleCanvas"));
	if (UOverlaySlot* CanvasSlot = Cast<UOverlaySlot>(Root->AddChild(GrappleCanvas)))
	{
		CanvasSlot->SetHorizontalAlignment(HAlign_Fill);
		CanvasSlot->SetVerticalAlignment(VAlign_Fill);
	}

	// A square whose diagonal is the marker size, outlined and not filled, turned onto its point.
	const float Side = GrappleMarkerSizePixels / UE_SQRT_2;
	FSlateBrush Brush;
	Brush.DrawAs = ESlateBrushDrawType::RoundedBox;
	Brush.TintColor = FSlateColor(FLinearColor::Transparent);
	Brush.OutlineSettings = FSlateBrushOutlineSettings(0.f, FSlateColor(GrappleMarkerColor), GrappleMarkerLineWidth);
	Brush.OutlineSettings.RoundingType = ESlateBrushRoundingType::FixedRadius;
	Brush.ImageSize = FVector2D(Side, Side);

	GrappleMarker = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("GrappleMarker"));
	GrappleMarker->SetBrush(Brush);
	GrappleMarker->SetRenderTransformPivot(FVector2D(0.5f, 0.5f));
	GrappleMarker->SetRenderTransformAngle(45.f);
	if (UCanvasPanelSlot* MarkerSlot = Cast<UCanvasPanelSlot>(GrappleCanvas->AddChild(GrappleMarker)))
	{
		MarkerSlot->SetAnchors(FAnchors(0.f, 0.f));
		MarkerSlot->SetAlignment(FVector2D(0.5f, 0.5f));
		MarkerSlot->SetAutoSize(false);
		MarkerSlot->SetSize(FVector2D(Side, Side));
	}

	GrappleHint = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("GrappleHint"));
	GrappleHint->SetColorAndOpacity(FSlateColor(GrappleMarkerColor));
	FSlateFontInfo HintFont = GrappleHint->GetFont();
	HintFont.Size = 12;
	GrappleHint->SetFont(HintFont);
	if (UCanvasPanelSlot* HintSlot = Cast<UCanvasPanelSlot>(GrappleCanvas->AddChild(GrappleHint)))
	{
		HintSlot->SetAnchors(FAnchors(0.f, 0.f));
		HintSlot->SetAlignment(FVector2D(0.5f, 0.f));
		HintSlot->SetAutoSize(true);
	}

	GrappleCanvas->SetVisibility(ESlateVisibility::Collapsed);
}

bool UCastleHudWidget::IsGrappleHintVisible() const
{
	if (!bGrappleMarkerVisible)
	{
		return false;
	}
	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	const UGrappleComponent* Grapple = Pawn ? Pawn->FindComponentByClass<UGrappleComponent>() : nullptr;
	return Grapple && Grapple->GetUseCount() < GrappleHintUses;
}

void UCastleHudWidget::UpdateGrappleMarker()
{
	APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	const UGrappleComponent* Grapple = Pawn ? Pawn->FindComponentByClass<UGrappleComponent>() : nullptr;
	const AGrappleAnchor* Anchor = Grapple ? Grapple->GetTargetAnchor() : nullptr;

	FVector2D Position = FVector2D::ZeroVector;
	bGrappleMarkerVisible = Anchor && Grapple->CanChain()
		&& UWidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition(PC, Anchor->GetMarkerLocation(), Position, false);
	if (bGrappleMarkerVisible)
	{
		GrappleMarkerPosition = Position;
	}

	if (!GrappleCanvas || !GrappleMarker || !GrappleHint)
	{
		return;
	}
	GrappleCanvas->SetVisibility(
		bGrappleMarkerVisible ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	if (!bGrappleMarkerVisible)
	{
		return;
	}
	if (UCanvasPanelSlot* MarkerSlot = Cast<UCanvasPanelSlot>(GrappleMarker->Slot))
	{
		MarkerSlot->SetPosition(Position);
	}
	if (UCanvasPanelSlot* HintSlot = Cast<UCanvasPanelSlot>(GrappleHint->Slot))
	{
		HintSlot->SetPosition(Position + FVector2D(0.f, GrappleMarkerSizePixels * 0.5f + 4.f));
	}
	GrappleHint->SetText(ApplyGamepadHint(GrappleHintText));
	GrappleHint->SetVisibility(
		IsGrappleHintVisible() ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
}

FLinearColor UCastleHudWidget::GetReticleColor() const
{
	return HitFlashRemaining > 0.f ? HitMarkerColor : ReticleColor;
}

void UCastleHudWidget::SetReticleAiming(bool bNewAiming)
{
	if (bReticleAiming == bNewAiming)
	{
		return;
	}

	bReticleAiming = bNewAiming;
	RefreshReticle();
}

void UCastleHudWidget::FlashHitMarker()
{
	HitFlashRemaining = HitFlashSeconds;
	RefreshReticle();
	RefreshDrawIndicator();
}

void UCastleHudWidget::PollPawnReticleState()
{
	const APlayerController* PC = GetOwningPlayer();
	const ACastleCharacter* Character = PC ? Cast<ACastleCharacter>(PC->GetPawn()) : nullptr;
	SetReticleAiming(Character != nullptr && Character->IsAiming());
}

FText UCastleHudWidget::GetMovementDebugText() const
{
	if (!ACastleCharacter::IsMovementDebugEnabled())
	{
		return FText::GetEmpty();
	}

	const APlayerController* PC = GetOwningPlayer();
	const ACastleCharacter* Character = PC ? Cast<ACastleCharacter>(PC->GetPawn()) : nullptr;
	return Character ? FText::FromString(Character->GetMovementDebugText()) : FText::GetEmpty();
}

void UCastleHudWidget::RefreshMovementDebug()
{
	if (!DebugText)
	{
		return;
	}

	const FText Line = GetMovementDebugText();
	DebugText->SetText(Line);
	DebugText->SetVisibility(Line.IsEmpty() ? ESlateVisibility::Collapsed : ESlateVisibility::HitTestInvisible);
}

void UCastleHudWidget::NativeTick(const FGeometry& MyGeometry, float DeltaSeconds)
{
	Super::NativeTick(MyGeometry, DeltaSeconds);

	PollPawnReticleState();
	PollPawnDrawState(MyGeometry);
	UpdateGrappleMarker();
	RefreshMovementDebug();

	if (HitFlashRemaining > 0.f)
	{
		HitFlashRemaining -= DeltaSeconds;
		if (HitFlashRemaining <= 0.f)
		{
			HitFlashRemaining = 0.f;
			RefreshReticle();
			RefreshDrawIndicator();
		}
	}
}

void UCastleHudWidget::HandleWeaponHit(AActor* /*HitActor*/, float /*DamageDealt*/)
{
	FlashHitMarker();
}

void UCastleHudWidget::NativeConstruct()
{
	Super::NativeConstruct();

	if (MissionCompleteText.IsEmpty())
	{
		MissionCompleteText = NSLOCTEXT("Castle", "MissionComplete", "Mission complete");
	}
	if (GrappleHintText.IsEmpty())
	{
		GrappleHintText = NSLOCTEXT("Castle", "GrappleHint", "Q");
	}

	BindToGame();
	RefreshObjective();
	RefreshAmmo();
	ClearPrompt();
}

void UCastleHudWidget::NativeDestruct()
{
	UnbindFromGame();

	Super::NativeDestruct();
}

void UCastleHudWidget::BindToGame()
{
	if (bBound)
	{
		return;
	}

	if (UMissionSubsystem* Missions = UMissionSubsystem::Get(this))
	{
		Missions->OnMissionStarted.AddDynamic(this, &UCastleHudWidget::HandleMissionStarted);
		Missions->OnObjectiveUpdated.AddDynamic(this, &UCastleHudWidget::HandleObjectiveUpdated);
		Missions->OnMissionComplete.AddDynamic(this, &UCastleHudWidget::HandleMissionComplete);
	}

	if (UWeaponComponent* Weapon = FindPawnWeapon())
	{
		Weapon->OnAmmoChanged.AddDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		Weapon->OnHit.AddDynamic(this, &UCastleHudWidget::HandleWeaponHit);
		BoundWeapon = Weapon;
	}

	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	if (UTakedownComponent* Takedown = Pawn ? Pawn->FindComponentByClass<UTakedownComponent>() : nullptr)
	{
		Takedown->OnTakedownPerformed.AddDynamic(this, &UCastleHudWidget::HandleTakedownPerformed);
	}

	bBound = true;
}

void UCastleHudWidget::UnbindFromGame()
{
	if (!bBound)
	{
		return;
	}

	if (UMissionSubsystem* Missions = UMissionSubsystem::Get(this))
	{
		Missions->OnMissionStarted.RemoveDynamic(this, &UCastleHudWidget::HandleMissionStarted);
		Missions->OnObjectiveUpdated.RemoveDynamic(this, &UCastleHudWidget::HandleObjectiveUpdated);
		Missions->OnMissionComplete.RemoveDynamic(this, &UCastleHudWidget::HandleMissionComplete);
	}

	if (BoundWeapon)
	{
		BoundWeapon->OnAmmoChanged.RemoveDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		BoundWeapon->OnHit.RemoveDynamic(this, &UCastleHudWidget::HandleWeaponHit);
		BoundWeapon = nullptr;
	}
	if (BoundBow)
	{
		BoundBow->OnHit.RemoveDynamic(this, &UCastleHudWidget::HandleBowHit);
		BoundBow = nullptr;
	}

	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	if (UTakedownComponent* Takedown = Pawn ? Pawn->FindComponentByClass<UTakedownComponent>() : nullptr)
	{
		Takedown->OnTakedownPerformed.RemoveDynamic(this, &UCastleHudWidget::HandleTakedownPerformed);
	}

	bBound = false;
}

UWeaponComponent* UCastleHudWidget::FindPawnWeapon() const
{
	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	return Pawn ? Pawn->FindComponentByClass<UWeaponComponent>() : nullptr;
}

FText UCastleHudWidget::FormatAmmo(int32 Magazine, int32 Reserve)
{
	return FText::FromString(FString::Printf(TEXT("%d / %d"), Magazine, Reserve));
}

FText UCastleHudWidget::BuildObjectiveText() const
{
	const UMissionSubsystem* Missions = UMissionSubsystem::Get(this);
	if (!Missions)
	{
		return FText::GetEmpty();
	}

	const UMissionDefinition* Mission = Missions->GetCurrentMission();
	if (!Mission || !Mission->bShowObjectiveText)
	{
		return FText::GetEmpty();
	}

	if (const UMissionObjective* Objective = Missions->GetCurrentObjective())
	{
		return Objective->Title;
	}

	return Missions->IsMissionComplete() ? MissionCompleteText : FText::GetEmpty();
}

void UCastleHudWidget::RefreshObjective()
{
	if (ObjectiveText)
	{
		ObjectiveText->SetText(BuildObjectiveText());
	}
}

void UCastleHudWidget::RefreshAmmo()
{
	// The pawn can gain a weapon component (or have it enabled) partway through the level.
	UWeaponComponent* Weapon = FindPawnWeapon();
	if (Weapon && Weapon != BoundWeapon)
	{
		if (BoundWeapon)
		{
			BoundWeapon->OnAmmoChanged.RemoveDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
			BoundWeapon->OnHit.RemoveDynamic(this, &UCastleHudWidget::HandleWeaponHit);
		}
		Weapon->OnAmmoChanged.AddDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		Weapon->OnHit.AddDynamic(this, &UCastleHudWidget::HandleWeaponHit);
		BoundWeapon = Weapon;
	}

	if (!AmmoText)
	{
		return;
	}

	if (!Weapon || !Weapon->HasWeapon())
	{
		AmmoText->SetText(FText::GetEmpty());
		return;
	}

	AmmoText->SetText(FormatAmmo(Weapon->CurrentAmmo, Weapon->ReserveAmmo));
}

void UCastleHudWidget::SetPrompt(FText Prompt)
{
	CurrentPrompt = ApplyGamepadHint(Prompt);
	if (PromptText)
	{
		PromptText->SetText(CurrentPrompt);
	}
}

FText UCastleHudWidget::ApplyGamepadHint(FText KeyboardHint) const
{
	const ACastlePlayerController* PC = Cast<ACastlePlayerController>(GetOwningPlayer());
	if (!PC || !PC->IsUsingGamepad() || KeyboardHint.IsEmpty())
	{
		return KeyboardHint;
	}

	FString Text = KeyboardHint.ToString();
	if (Text.Equals(TEXT("Q")))
	{
		// The grapple marker's bare "Q" hint; RB fires IA_Grapple on a gamepad.
		return NSLOCTEXT("Castle", "GrappleHintGamepad", "RB");
	}

	// Takedown and interact share the Y face button; both prompts read the same on a pad.
	Text.ReplaceInline(TEXT("[F]"), TEXT("[Y]"));
	Text.ReplaceInline(TEXT("[E]"), TEXT("[Y]"));
	return FText::FromString(Text);
}

void UCastleHudWidget::ClearPrompt()
{
	SetPrompt(FText::GetEmpty());
}

void UCastleHudWidget::HandleMissionStarted(UMissionDefinition* /*Mission*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleObjectiveUpdated(UMissionObjective* /*Objective*/, int32 /*ObjectiveIndex*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleMissionComplete(UMissionDefinition* /*Mission*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleAmmoChanged(int32 /*Magazine*/, int32 /*Reserve*/)
{
	RefreshAmmo();
}

void UCastleHudWidget::HandleTakedownPerformed(AActor* /*Target*/)
{
	// The guard is down; whatever prompt pointed at him is stale.
	ClearPrompt();
}
