// Copyright Epic Games, Inc. All Rights Reserved.

#include "UI/CastleHudWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Castle.h"
#include "Combat/TakedownComponent.h"
#include "Combat/WeaponComponent.h"
#include "Components/Border.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/TextBlock.h"
#include "GameFramework/Pawn.h"
#include "GameFramework/PlayerController.h"
#include "Mission/MissionDefinition.h"
#include "Mission/MissionObjective.h"
#include "Mission/MissionSubsystem.h"
#include "Player/CastleCharacter.h"

TSharedRef<SWidget> UCastleHudWidget::RebuildWidget()
{
	// WBP_Hud is generated by a script and has no designer layout, so build the four driven
	// widgets here when nothing is bound.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("HudRoot"));
		WidgetTree->RootWidget = Root;

		auto AddText = [this, Root](TObjectPtr<UTextBlock>& TextSlot, const TCHAR* Name,
			EHorizontalAlignment HAlign, EVerticalAlignment VAlign, const FMargin& TextPadding)
		{
			if (!TextSlot)
			{
				TextSlot = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), Name);
			}
			if (UOverlaySlot* OverlaySlot = Cast<UOverlaySlot>(Root->AddChild(TextSlot)))
			{
				OverlaySlot->SetHorizontalAlignment(HAlign);
				OverlaySlot->SetVerticalAlignment(VAlign);
				OverlaySlot->SetPadding(TextPadding);
			}
		};

		AddText(ObjectiveText, TEXT("ObjectiveText"), HAlign_Left, VAlign_Top, FMargin(48.f, 48.f, 0.f, 0.f));
		AddText(AmmoText, TEXT("AmmoText"), HAlign_Right, VAlign_Bottom, FMargin(0.f, 0.f, 48.f, 48.f));
		AddText(PromptText, TEXT("PromptText"), HAlign_Center, VAlign_Center, FMargin(0.f, 120.f, 0.f, 0.f));

		BuildCrosshair(Root);
	}

	return Super::RebuildWidget();
}

void UCastleHudWidget::BuildCrosshair(UOverlay* Root)
{
	if (!WidgetTree || !Root)
	{
		return;
	}

	if (!Crosshair)
	{
		Crosshair = WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(), TEXT("Crosshair"));
	}

	// The canvas fills the screen and every bar is anchored to its centre, which is the only
	// way to land on the exact centre pixel regardless of resolution.
	if (UOverlaySlot* CrosshairSlot = Cast<UOverlaySlot>(Root->AddChild(Crosshair)))
	{
		CrosshairSlot->SetHorizontalAlignment(HAlign_Fill);
		CrosshairSlot->SetVerticalAlignment(VAlign_Fill);
	}

	static const TCHAR* BarNames[] = { TEXT("CrosshairTop"), TEXT("CrosshairBottom"),
		TEXT("CrosshairLeft"), TEXT("CrosshairRight") };

	CrosshairBars.Reset();
	for (const TCHAR* BarName : BarNames)
	{
		UBorder* Bar = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), BarName);
		Bar->SetPadding(FMargin(0.f));
		if (UCanvasPanelSlot* BarSlot = Cast<UCanvasPanelSlot>(Crosshair->AddChild(Bar)))
		{
			BarSlot->SetAnchors(FAnchors(0.5f, 0.5f));
			BarSlot->SetAlignment(FVector2D(0.5f, 0.5f));
			BarSlot->SetAutoSize(false);
		}
		CrosshairBars.Add(Bar);
	}

	RefreshCrosshair();
}

void UCastleHudWidget::RefreshCrosshair()
{
	if (CrosshairBars.Num() < 4)
	{
		return;
	}

	// Centre of a bar sits a gap plus half its own length away from the middle.
	const float Offset = GetCrosshairGap() + BarLengthPixels * 0.5f;
	const FVector2D VerticalSize(BarThicknessPixels, BarLengthPixels);
	const FVector2D HorizontalSize(BarLengthPixels, BarThicknessPixels);

	const FVector2D Sizes[] = { VerticalSize, VerticalSize, HorizontalSize, HorizontalSize };
	const FVector2D Positions[] = {
		FVector2D(0.f, -Offset), FVector2D(0.f, Offset),
		FVector2D(-Offset, 0.f), FVector2D(Offset, 0.f) };

	const FLinearColor Color = GetCrosshairColor();

	for (int32 Index = 0; Index < 4; ++Index)
	{
		UBorder* Bar = CrosshairBars[Index];
		if (!Bar)
		{
			continue;
		}

		Bar->SetBrushColor(Color);
		if (UCanvasPanelSlot* BarSlot = Cast<UCanvasPanelSlot>(Bar->Slot))
		{
			BarSlot->SetSize(Sizes[Index]);
			BarSlot->SetPosition(Positions[Index]);
		}
	}

	if (Crosshair)
	{
		Crosshair->SetRenderOpacity(bCrosshairSprinting ? SprintOpacity : 1.f);
		Crosshair->SetVisibility(IsCrosshairVisible()
			? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	}
}

FLinearColor UCastleHudWidget::GetCrosshairColor() const
{
	return HitFlashRemaining > 0.f ? HitMarkerColor : CrosshairColor;
}

bool UCastleHudWidget::IsCrosshairVisible() const
{
	const UWeaponComponent* Weapon = FindPawnWeapon();
	return Weapon != nullptr && Weapon->HasWeapon();
}

void UCastleHudWidget::SetCrosshairAiming(bool bNewAiming)
{
	if (bCrosshairAiming == bNewAiming)
	{
		return;
	}

	bCrosshairAiming = bNewAiming;
	RefreshCrosshair();
}

void UCastleHudWidget::SetCrosshairSprinting(bool bNewSprinting)
{
	if (bCrosshairSprinting == bNewSprinting)
	{
		return;
	}

	bCrosshairSprinting = bNewSprinting;
	RefreshCrosshair();
}

void UCastleHudWidget::FlashHitMarker()
{
	HitFlashRemaining = HitFlashSeconds;
	RefreshCrosshair();
}

void UCastleHudWidget::PollPawnCrosshairState()
{
	const APlayerController* PC = GetOwningPlayer();
	const ACastleCharacter* Character = PC ? Cast<ACastleCharacter>(PC->GetPawn()) : nullptr;
	if (!Character)
	{
		return;
	}

	SetCrosshairAiming(Character->IsAiming());
	SetCrosshairSprinting(Character->IsSprinting());
}

void UCastleHudWidget::NativeTick(const FGeometry& MyGeometry, float DeltaSeconds)
{
	Super::NativeTick(MyGeometry, DeltaSeconds);

	PollPawnCrosshairState();

	if (HitFlashRemaining > 0.f)
	{
		HitFlashRemaining -= DeltaSeconds;
		if (HitFlashRemaining <= 0.f)
		{
			HitFlashRemaining = 0.f;
			RefreshCrosshair();
		}
	}
}

void UCastleHudWidget::HandleWeaponHit(AActor* /*HitActor*/, float /*DamageDealt*/)
{
	FlashHitMarker();
}

void UCastleHudWidget::NativeConstruct()
{
	Super::NativeConstruct();

	if (MissionCompleteText.IsEmpty())
	{
		MissionCompleteText = NSLOCTEXT("Castle", "MissionComplete", "Mission complete");
	}

	BindToGame();
	RefreshObjective();
	RefreshAmmo();
	ClearPrompt();
}

void UCastleHudWidget::NativeDestruct()
{
	UnbindFromGame();

	Super::NativeDestruct();
}

void UCastleHudWidget::BindToGame()
{
	if (bBound)
	{
		return;
	}

	if (UMissionSubsystem* Missions = UMissionSubsystem::Get(this))
	{
		Missions->OnMissionStarted.AddDynamic(this, &UCastleHudWidget::HandleMissionStarted);
		Missions->OnObjectiveUpdated.AddDynamic(this, &UCastleHudWidget::HandleObjectiveUpdated);
		Missions->OnMissionComplete.AddDynamic(this, &UCastleHudWidget::HandleMissionComplete);
	}

	if (UWeaponComponent* Weapon = FindPawnWeapon())
	{
		Weapon->OnAmmoChanged.AddDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		Weapon->OnHit.AddDynamic(this, &UCastleHudWidget::HandleWeaponHit);
		BoundWeapon = Weapon;
	}

	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	if (UTakedownComponent* Takedown = Pawn ? Pawn->FindComponentByClass<UTakedownComponent>() : nullptr)
	{
		Takedown->OnTakedownPerformed.AddDynamic(this, &UCastleHudWidget::HandleTakedownPerformed);
	}

	bBound = true;
}

void UCastleHudWidget::UnbindFromGame()
{
	if (!bBound)
	{
		return;
	}

	if (UMissionSubsystem* Missions = UMissionSubsystem::Get(this))
	{
		Missions->OnMissionStarted.RemoveDynamic(this, &UCastleHudWidget::HandleMissionStarted);
		Missions->OnObjectiveUpdated.RemoveDynamic(this, &UCastleHudWidget::HandleObjectiveUpdated);
		Missions->OnMissionComplete.RemoveDynamic(this, &UCastleHudWidget::HandleMissionComplete);
	}

	if (BoundWeapon)
	{
		BoundWeapon->OnAmmoChanged.RemoveDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		BoundWeapon->OnHit.RemoveDynamic(this, &UCastleHudWidget::HandleWeaponHit);
		BoundWeapon = nullptr;
	}

	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	if (UTakedownComponent* Takedown = Pawn ? Pawn->FindComponentByClass<UTakedownComponent>() : nullptr)
	{
		Takedown->OnTakedownPerformed.RemoveDynamic(this, &UCastleHudWidget::HandleTakedownPerformed);
	}

	bBound = false;
}

UWeaponComponent* UCastleHudWidget::FindPawnWeapon() const
{
	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	return Pawn ? Pawn->FindComponentByClass<UWeaponComponent>() : nullptr;
}

FText UCastleHudWidget::FormatAmmo(int32 Magazine, int32 Reserve)
{
	return FText::FromString(FString::Printf(TEXT("%d / %d"), Magazine, Reserve));
}

FText UCastleHudWidget::BuildObjectiveText() const
{
	const UMissionSubsystem* Missions = UMissionSubsystem::Get(this);
	if (!Missions)
	{
		return FText::GetEmpty();
	}

	const UMissionDefinition* Mission = Missions->GetCurrentMission();
	if (!Mission || !Mission->bShowObjectiveText)
	{
		return FText::GetEmpty();
	}

	if (const UMissionObjective* Objective = Missions->GetCurrentObjective())
	{
		return Objective->Title;
	}

	return Missions->IsMissionComplete() ? MissionCompleteText : FText::GetEmpty();
}

void UCastleHudWidget::RefreshObjective()
{
	if (ObjectiveText)
	{
		ObjectiveText->SetText(BuildObjectiveText());
	}
}

void UCastleHudWidget::RefreshAmmo()
{
	// The pawn can gain a weapon component (or have it enabled) partway through the level.
	UWeaponComponent* Weapon = FindPawnWeapon();
	if (Weapon && Weapon != BoundWeapon)
	{
		if (BoundWeapon)
		{
			BoundWeapon->OnAmmoChanged.RemoveDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
			BoundWeapon->OnHit.RemoveDynamic(this, &UCastleHudWidget::HandleWeaponHit);
		}
		Weapon->OnAmmoChanged.AddDynamic(this, &UCastleHudWidget::HandleAmmoChanged);
		Weapon->OnHit.AddDynamic(this, &UCastleHudWidget::HandleWeaponHit);
		BoundWeapon = Weapon;
	}

	// Picking the pistol up is what makes the crosshair appear.
	RefreshCrosshair();

	if (!AmmoText)
	{
		return;
	}

	if (!Weapon || !Weapon->HasWeapon())
	{
		AmmoText->SetText(FText::GetEmpty());
		return;
	}

	AmmoText->SetText(FormatAmmo(Weapon->CurrentAmmo, Weapon->ReserveAmmo));
}

void UCastleHudWidget::SetPrompt(FText Prompt)
{
	CurrentPrompt = Prompt;
	if (PromptText)
	{
		PromptText->SetText(CurrentPrompt);
	}
}

void UCastleHudWidget::ClearPrompt()
{
	SetPrompt(FText::GetEmpty());
}

void UCastleHudWidget::HandleMissionStarted(UMissionDefinition* /*Mission*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleObjectiveUpdated(UMissionObjective* /*Objective*/, int32 /*ObjectiveIndex*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleMissionComplete(UMissionDefinition* /*Mission*/)
{
	RefreshObjective();
}

void UCastleHudWidget::HandleAmmoChanged(int32 /*Magazine*/, int32 /*Reserve*/)
{
	RefreshAmmo();
}

void UCastleHudWidget::HandleTakedownPerformed(AActor* /*Target*/)
{
	// The guard is down; whatever prompt pointed at him is stale.
	ClearPrompt();
}
