// Copyright Epic Games, Inc. All Rights Reserved.

#include "UI/MissionEndCardWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Castle.h"
#include "Components/Border.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "Mission/MissionDefinition.h"

TSharedRef<SWidget> UMissionEndCardWidget::RebuildWidget()
{
	// WBP_EndCard is generated by a script and has no designer layout, so build one here.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("EndCardRoot"));
		WidgetTree->RootWidget = Root;

		if (!Background)
		{
			Background = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("Background"));
		}
		Background->SetBrushColor(FLinearColor::Black);
		if (UOverlaySlot* BackgroundSlot = Cast<UOverlaySlot>(Root->AddChild(Background)))
		{
			BackgroundSlot->SetHorizontalAlignment(HAlign_Fill);
			BackgroundSlot->SetVerticalAlignment(VAlign_Fill);
		}

		UVerticalBox* Stack = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("EndCardStack"));
		if (UOverlaySlot* StackSlot = Cast<UOverlaySlot>(Root->AddChild(Stack)))
		{
			StackSlot->SetHorizontalAlignment(HAlign_Center);
			StackSlot->SetVerticalAlignment(VAlign_Center);
		}

		auto AddText = [this, Stack](TObjectPtr<UTextBlock>& TextSlot, const TCHAR* Name,
			int32 FontSize, const FMargin& Padding)
		{
			if (!TextSlot)
			{
				TextSlot = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), Name);
			}

			FSlateFontInfo Font = TextSlot->GetFont();
			Font.Size = FontSize;
			TextSlot->SetFont(Font);
			TextSlot->SetJustification(ETextJustify::Center);

			if (UVerticalBoxSlot* Entry = Cast<UVerticalBoxSlot>(Stack->AddChild(TextSlot)))
			{
				Entry->SetHorizontalAlignment(HAlign_Center);
				Entry->SetPadding(Padding);
			}
		};

		// The mission name is the headline; the line under it is Frank's, so it reads smaller.
		AddText(MissionNameText, TEXT("MissionNameText"), 56, FMargin(0.f, 0.f, 0.f, 24.f));
		AddText(LineText, TEXT("LineText"), 22, FMargin(0.f, 0.f, 0.f, 0.f));
		AddText(PromptText, TEXT("PromptText"), 16, FMargin(0.f, 96.f, 0.f, 0.f));
	}

	return Super::RebuildWidget();
}

void UMissionEndCardWidget::ApplyMissionText()
{
	if (MissionNameText)
	{
		MissionNameText->SetText(CurrentMission ? CurrentMission->MissionName : FText::GetEmpty());
	}
	if (LineText)
	{
		LineText->SetText(CurrentMission ? CurrentMission->EndCardLine : FText::GetEmpty());
	}
	if (PromptText)
	{
		PromptText->SetText(PromptLabel);
	}
}

void UMissionEndCardWidget::Play(UMissionDefinition* Mission)
{
	CurrentMission = Mission;
	PromptLabel = FText::GetEmpty();
	bWaitForInput = false;
	ElapsedSeconds = 0.f;
	bIsPlaying = true;

	ApplyMissionText();

	if (!Mission)
	{
		UE_LOG(LogCastle, Warning, TEXT("%s: end card played with no mission."), *GetName());
	}

	// A zero hold is a legitimate "skip the card" setting, so finish before the first tick.
	if (EndCardSeconds <= 0.f)
	{
		Finish();
	}
}

void UMissionEndCardWidget::PlayAndWaitForInput(UMissionDefinition* Mission, FText Prompt)
{
	Play(Mission);

	// Play may already have finished on a zero hold; the campaign end still wants the key.
	CurrentMission = Mission;
	PromptLabel = Prompt;
	bWaitForInput = true;
	bIsPlaying = true;
	ElapsedSeconds = 0.f;

	ApplyMissionText();

	SetIsFocusable(true);
	SetKeyboardFocus();
}

void UMissionEndCardWidget::NativeTick(const FGeometry& MyGeometry, float InDeltaTime)
{
	Super::NativeTick(MyGeometry, InDeltaTime);

	if (!bIsPlaying || bWaitForInput)
	{
		return;
	}

	ElapsedSeconds += InDeltaTime;
	if (ElapsedSeconds >= EndCardSeconds)
	{
		Finish();
	}
}

FReply UMissionEndCardWidget::NativeOnKeyDown(const FGeometry& InGeometry, const FKeyEvent& InKeyEvent)
{
	if (bIsPlaying && bWaitForInput)
	{
		Finish();
		return FReply::Handled();
	}

	return Super::NativeOnKeyDown(InGeometry, InKeyEvent);
}

FReply UMissionEndCardWidget::NativeOnMouseButtonDown(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
	if (bIsPlaying && bWaitForInput)
	{
		Finish();
		return FReply::Handled();
	}

	return Super::NativeOnMouseButtonDown(InGeometry, InMouseEvent);
}

void UMissionEndCardWidget::Finish()
{
	if (!bIsPlaying)
	{
		return;
	}

	bIsPlaying = false;
	bWaitForInput = false;

	OnEndCardFinished.Broadcast(CurrentMission);
}
