// Copyright Epic Games, Inc. All Rights Reserved.

#include "UI/HawkeyeHudWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Brushes/SlateColorBrush.h"
#include "Hawkeye.h"
#include "HawkeyePlayerController.h"
#include "Combat/BowComponent.h"
#include "Combat/TakedownComponent.h"
#include "Combat/WeaponComponent.h"
#include "Blueprint/WidgetLayoutLibrary.h"
#include "Components/Border.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/Image.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/TextBlock.h"
#include "GameFramework/Pawn.h"
#include "GameFramework/PlayerController.h"
#include "Mission/MissionDefinition.h"
#include "Mission/MissionObjective.h"
#include "Mission/MissionSubsystem.h"
#include "Player/HawkeyeCharacter.h"
#include "Player/GrappleComponent.h"
#include "UI/ChallengePanelWidget.h"
#include "UI/CrimePanelWidget.h"
#include "UI/HawkeyeHotbarWidget.h"
#include "UI/HawkeyeObjectiveWidget.h"
#include "UI/HawkeyeThugOverheadWidget.h"
#include "UI/HawkeyeQuiverWheelWidget.h"
#include "World/GrappleAnchor.h"
#include "EngineUtils.h"
#include "Partner/HawkeyePartnerController.h"
#include "Brushes/SlateRoundedBoxBrush.h"
#include "Components/HorizontalBox.h"
#include "Components/HorizontalBoxSlot.h"
#include "Components/SizeBox.h"
#include "Phone/PhoneSubsystem.h"
#include "Settings/HawkeyeSettingsSubsystem.h"

TSharedRef<SWidget> UHawkeyeHudWidget::RebuildWidget()
{
	// WBP_Hud is generated by a script and has no designer layout, so build the four driven
	// widgets here when nothing is bound.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("HudRoot"));
		WidgetTree->RootWidget = Root;

		auto AddText = [this, Root](TObjectPtr<UTextBlock>& TextSlot, const TCHAR* Name,
			EHorizontalAlignment HAlign, EVerticalAlignment VAlign, const FMargin& TextPadding)
		{
			if (!TextSlot)
			{
				TextSlot = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), Name);
			}
			if (UOverlaySlot* OverlaySlot = Cast<UOverlaySlot>(Root->AddChild(TextSlot)))
			{
				OverlaySlot->SetHorizontalAlignment(HAlign);
				OverlaySlot->SetVerticalAlignment(VAlign);
				OverlaySlot->SetPadding(TextPadding);
			}
		};

		AddText(ObjectiveText, TEXT("ObjectiveText"), HAlign_Left, VAlign_Top, FMargin(48.f, 48.f, 0.f, 0.f));
		AddText(AmmoText, TEXT("AmmoText"), HAlign_Right, VAlign_Bottom, FMargin(0.f, 0.f, 48.f, 48.f));
		AddText(PromptText, TEXT("PromptText"), HAlign_Center, VAlign_Center, FMargin(0.f, 120.f, 0.f, 0.f));
		AddText(DebugText, TEXT("DebugText"), HAlign_Left, VAlign_Top, FMargin(48.f, 80.f, 0.f, 0.f));
		DebugText->SetVisibility(ESlateVisibility::Collapsed);

		BuildReticle(Root);
		BuildGrappleMarker(Root);
		BuildPartnerWidgets(Root);
		BuildPhoneBadge(Root);
		BuildComboCounter(Root);

		// Top right, clear of the objective line (top left) and the compass (top centre).
		ChallengePanel = WidgetTree->ConstructWidget<UChallengePanelWidget>(UChallengePanelWidget::StaticClass(), TEXT("ChallengePanelHud"));
		ChallengePanel->SetVisibility(ESlateVisibility::HitTestInvisible);
		if (UOverlaySlot* PanelSlot = Cast<UOverlaySlot>(Root->AddChild(ChallengePanel)))
		{
			PanelSlot->SetHorizontalAlignment(HAlign_Right);
			PanelSlot->SetVerticalAlignment(VAlign_Top);
			PanelSlot->SetPadding(FMargin(0.f, 48.f, 48.f, 0.f));
		}

		// Under the challenge panel's place: a crime pauses while a challenge runs, so they rarely share.
		CrimePanel = WidgetTree->ConstructWidget<UCrimePanelWidget>(UCrimePanelWidget::StaticClass(), TEXT("CrimePanelHud"));
		CrimePanel->SetVisibility(ESlateVisibility::HitTestInvisible);
		if (UOverlaySlot* CrimeSlot = Cast<UOverlaySlot>(Root->AddChild(CrimePanel)))
		{
			CrimeSlot->SetHorizontalAlignment(HAlign_Right);
			CrimeSlot->SetVerticalAlignment(VAlign_Top);
			CrimeSlot->SetPadding(FMargin(0.f, 190.f, 48.f, 0.f));
		}

		// Under the objective marker and the hotbar: the thugs' glyphs and health bars.
		ThugOverhead = WidgetTree->ConstructWidget<UHawkeyeThugOverheadWidget>(
			UHawkeyeThugOverheadWidget::StaticClass(), TEXT("ThugOverhead"));
		ThugOverhead->SetVisibility(ESlateVisibility::HitTestInvisible);
		if (UOverlaySlot* OverheadSlot = Cast<UOverlaySlot>(Root->AddChild(ThugOverhead)))
		{
			OverheadSlot->SetHorizontalAlignment(HAlign_Fill);
			OverheadSlot->SetVerticalAlignment(VAlign_Fill);
		}

		ObjectiveMarker = WidgetTree->ConstructWidget<UHawkeyeObjectiveWidget>(
			UHawkeyeObjectiveWidget::StaticClass(), TEXT("ObjectiveMarker"));
		ObjectiveMarker->SetVisibility(ESlateVisibility::HitTestInvisible);
		if (UOverlaySlot* MarkerSlot = Cast<UOverlaySlot>(Root->AddChild(ObjectiveMarker)))
		{
			MarkerSlot->SetHorizontalAlignment(HAlign_Fill);
			MarkerSlot->SetVerticalAlignment(VAlign_Fill);
		}

		// The hotbar is its own widget so it can be styled and tested on its own, but it lives
		// inside the HUD's overlay rather than being a second thing the controller manages.
		TSubclassOf<UHawkeyeHotbarWidget> HotbarClass = HotbarWidgetClass;
		if (!HotbarClass)
		{
			HotbarClass = UHawkeyeHotbarWidget::StaticClass();
		}
		Hotbar = WidgetTree->ConstructWidget<UHawkeyeHotbarWidget>(HotbarClass, TEXT("Hotbar"));
		if (UOverlaySlot* HotbarSlot = Cast<UOverlaySlot>(Root->AddChild(Hotbar)))
		{
			HotbarSlot->SetHorizontalAlignment(HAlign_Center);
			HotbarSlot->SetVerticalAlignment(VAlign_Bottom);
			HotbarSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 24.f));
		}

		// Last, so the wheel draws over everything else while it is open.
		QuiverWheel = WidgetTree->ConstructWidget<UHawkeyeQuiverWheelWidget>(
			UHawkeyeQuiverWheelWidget::StaticClass(), TEXT("QuiverWheel"));
		if (UOverlaySlot* WheelSlot = Cast<UOverlaySlot>(Root->AddChild(QuiverWheel)))
		{
			WheelSlot->SetHorizontalAlignment(HAlign_Fill);
			WheelSlot->SetVerticalAlignment(VAlign_Fill);
		}
	}

	return Super::RebuildWidget();
}

void UHawkeyeHudWidget::BuildPhoneBadge(UOverlay* Root)
{
	if (!WidgetTree || !Root)
	{
		return;
	}
	UHorizontalBox* Badge = WidgetTree->ConstructWidget<UHorizontalBox>(UHorizontalBox::StaticClass(), TEXT("PhoneBadge"));
	PhoneBadge = Badge;
	if (UOverlaySlot* BadgeSlot = Cast<UOverlaySlot>(Root->AddChild(Badge)))
	{
		BadgeSlot->SetHorizontalAlignment(HAlign_Right);
		BadgeSlot->SetVerticalAlignment(VAlign_Bottom);
		BadgeSlot->SetPadding(FMargin(0.f, 0.f, 48.f, 96.f));
	}

	// The outline of a phone: a hollow rounded box, taller than wide.
	USizeBox* IconSize = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("PhoneIconSize"));
	IconSize->SetWidthOverride(15.f);
	IconSize->SetHeightOverride(25.f);
	PhoneIcon = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("PhoneIcon"));
	PhoneIcon->SetBrush(FSlateRoundedBoxBrush(FLinearColor::Transparent, 3.f, FLinearColor::White, 1.5f));
	IconSize->AddChild(PhoneIcon);
	if (UHorizontalBoxSlot* IconSlot = Cast<UHorizontalBoxSlot>(Badge->AddChild(IconSize)))
	{
		IconSlot->SetVerticalAlignment(VAlign_Center);
	}

	PhoneBadgeText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("PhoneBadgeText"));
	FSlateFontInfo Font = PhoneBadgeText->GetFont();
	Font.Size = 16;
	PhoneBadgeText->SetFont(Font);
	PhoneBadgeText->SetColorAndOpacity(FSlateColor(ReticleColor));
	if (UHorizontalBoxSlot* CountSlot = Cast<UHorizontalBoxSlot>(Badge->AddChild(PhoneBadgeText)))
	{
		CountSlot->SetVerticalAlignment(VAlign_Center);
		CountSlot->SetPadding(FMargin(8.f, 0.f, 0.f, 0.f));
	}
	UpdatePhoneBadge();
}

void UHawkeyeHudWidget::BuildComboCounter(UOverlay* Root)
{
	if (!WidgetTree || !Root)
	{
		return;
	}
	ComboText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("ComboText"));
	FSlateFontInfo Font = ComboText->GetFont();
	Font.Size = 22;
	ComboText->SetFont(Font);
	ComboText->SetColorAndOpacity(FSlateColor(ComboColor));
	ComboText->SetShadowOffset(FVector2D(1.f, 1.f));
	ComboText->SetShadowColorAndOpacity(FLinearColor(0.f, 0.f, 0.f, 0.6f));
	ComboText->SetVisibility(ESlateVisibility::HitTestInvisible);
	if (UOverlaySlot* ComboSlot = Cast<UOverlaySlot>(Root->AddChild(ComboText)))
	{
		// Right of the reticle and a little above it, where the eye already is in a fight.
		ComboSlot->SetHorizontalAlignment(HAlign_Right);
		ComboSlot->SetVerticalAlignment(VAlign_Center);
		ComboSlot->SetPadding(FMargin(0.f, 0.f, 220.f, 120.f));
	}
	UpdateComboCounter();
}

FText UHawkeyeHudWidget::FormatComboCount(int32 Count)
{
	return Count >= 2 ? FText::FromString(FString::Printf(TEXT("x%d"), Count)) : FText::GetEmpty();
}

void UHawkeyeHudWidget::UpdateComboCounter()
{
	const APlayerController* PC = GetOwningPlayer();
	const AHawkeyeCharacter* Character = PC ? Cast<AHawkeyeCharacter>(PC->GetPawn()) : nullptr;
	const int32 Count = Character ? Character->GetComboCount() : 0;
	const bool bBonus = Character && Character->IsComboBonusActive();
	if (!ComboText || (Count == ShownComboCount && bBonus == bShownComboBonus))
	{
		return;
	}
	ShownComboCount = Count;
	bShownComboBonus = bBonus;
	ComboText->SetText(FormatComboCount(Count));
	ComboText->SetColorAndOpacity(FSlateColor(bBonus ? ComboBonusColor : ComboColor));
	// The glow: a purple halo in place of the drop shadow.
	ComboText->SetShadowOffset(bBonus ? FVector2D::ZeroVector : FVector2D(1.f, 1.f));
	ComboText->SetShadowColorAndOpacity(bBonus ? FLinearColor(0.6f, 0.2f, 1.f, 0.9f) : FLinearColor(0.f, 0.f, 0.f, 0.6f));
	FSlateFontInfo Font = ComboText->GetFont();
	Font.OutlineSettings.OutlineSize = bBonus ? 2 : 0;
	Font.OutlineSettings.OutlineColor = FLinearColor(0.55f, 0.15f, 1.f, 0.85f);
	ComboText->SetFont(Font);
}

void UHawkeyeHudWidget::UpdatePhoneBadge()
{
	const UPhoneSubsystem* Phone = UPhoneSubsystem::Get(this);
	const int32 Count = Phone ? Phone->GetUnreadCount() : 0;
	if (Count == PhoneBadgeCount)
	{
		return;
	}
	PhoneBadgeCount = Count;
	if (PhoneBadgeText)
	{
		PhoneBadgeText->SetText(Count > 0 ? FText::AsNumber(Count) : FText::GetEmpty());
	}
	if (PhoneIcon)
	{
		// Dim until something is waiting, then Kate purple (the palette's).
		const FLinearColor Outline = Count > 0 ? ReticleColor : FLinearColor(1.f, 1.f, 1.f, 0.45f);
		PhoneIcon->SetBrush(FSlateRoundedBoxBrush(FLinearColor::Transparent, 3.f, Outline, 1.5f));
	}
}

void UHawkeyeHudWidget::SetQuiverWheelState(bool bOpen, int32 QuiverSlot)
{
	if (QuiverWheel)
	{
		QuiverWheel->SetWheelState(bOpen, QuiverSlot);
	}
}

void UHawkeyeHudWidget::BuildReticle(UOverlay* Root)
{
	if (!WidgetTree || !Root)
	{
		return;
	}

	if (!Reticle)
	{
		Reticle = WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(), TEXT("Reticle"));
	}

	// The canvas fills the screen and the dot is anchored to its centre, which is the only way
	// to land on the exact centre pixel regardless of resolution.
	if (UOverlaySlot* ReticleSlot = Cast<UOverlaySlot>(Root->AddChild(Reticle)))
	{
		ReticleSlot->SetHorizontalAlignment(HAlign_Fill);
		ReticleSlot->SetVerticalAlignment(VAlign_Fill);
	}

	ReticleDot = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("ReticleDot"));
	ReticleDot->SetPadding(FMargin(0.f));
	if (UCanvasPanelSlot* DotSlot = Cast<UCanvasPanelSlot>(Reticle->AddChild(ReticleDot)))
	{
		DotSlot->SetAnchors(FAnchors(0.5f, 0.5f));
		DotSlot->SetAlignment(FVector2D(0.5f, 0.5f));
		DotSlot->SetAutoSize(false);
		DotSlot->SetPosition(FVector2D::ZeroVector);
	}

	// The spread ring: a transparent box with a round outline, sized every frame to the cone.
	FSlateBrush RingBrush;
	RingBrush.DrawAs = ESlateBrushDrawType::RoundedBox;
	RingBrush.TintColor = FSlateColor(FLinearColor::Transparent);
	RingBrush.OutlineSettings = FSlateBrushOutlineSettings(0.f, FSlateColor(ReticleColor), RingLineWidth);
	RingBrush.OutlineSettings.RoundingType = ESlateBrushRoundingType::HalfHeightRadius;
	ReticleRing = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("ReticleRing"));
	ReticleRing->SetBrush(RingBrush);
	if (UCanvasPanelSlot* RingSlot = Cast<UCanvasPanelSlot>(Reticle->AddChild(ReticleRing)))
	{
		RingSlot->SetAnchors(FAnchors(0.5f, 0.5f));
		RingSlot->SetAlignment(FVector2D(0.5f, 0.5f));
		RingSlot->SetAutoSize(false);
		RingSlot->SetPosition(FVector2D::ZeroVector);
	}

	// The draw bar: a dim track and a fill anchored to its left end.
	auto AddBar = [this](const TCHAR* Name, const FLinearColor& Color)
	{
		UBorder* Bar = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), Name);
		Bar->SetBrush(FSlateColorBrush(FLinearColor::White));
		Bar->SetBrushColor(Color);
		Bar->SetPadding(FMargin(0.f));
		if (UCanvasPanelSlot* BarSlot = Cast<UCanvasPanelSlot>(Reticle->AddChild(Bar)))
		{
			BarSlot->SetAnchors(FAnchors(0.5f, 0.5f));
			BarSlot->SetAlignment(FVector2D(0.f, 0.5f));
			BarSlot->SetAutoSize(false);
			BarSlot->SetPosition(FVector2D(-DrawBarWidth * 0.5f, DrawBarOffset));
			BarSlot->SetSize(FVector2D(DrawBarWidth, DrawBarHeight));
		}
		return Bar;
	};
	DrawBarBack = AddBar(TEXT("DrawBarBack"), FLinearColor(0.f, 0.f, 0.f, 0.45f));
	DrawBarFill = AddBar(TEXT("DrawBarFill"), ReticleColor);

	RefreshReticle();
	RefreshDrawIndicator();
}

float UHawkeyeHudWidget::ComputeSpreadRingRadius(float SpreadDegrees, float FovDegrees, float ViewportWidth, float Distance)
{
	const float HalfFov = FMath::DegreesToRadians(FMath::Clamp(FovDegrees, 1.f, 170.f) * 0.5f);
	const float WorldRadius = Distance * FMath::Tan(FMath::DegreesToRadians(FMath::Max(SpreadDegrees, 0.f)));
	const float HalfWidthAtDistance = Distance * FMath::Tan(HalfFov);
	return HalfWidthAtDistance > 0.f ? WorldRadius / HalfWidthAtDistance * ViewportWidth * 0.5f : 0.f;
}

void UHawkeyeHudWidget::SetDrawState(bool bInDrawing, float InFraction, float InRingRadius, bool bInPerfect)
{
	bDrawing = bInDrawing;
	DrawFraction = bInDrawing ? FMath::Clamp(InFraction, 0.f, 1.f) : 0.f;
	bPerfectWindow = bInDrawing && bInPerfect;
	RingRadius = bInDrawing ? FMath::Max(InRingRadius, MinRingRadius) : 0.f;
	RefreshDrawIndicator();
}

void UHawkeyeHudWidget::RefreshDrawIndicator()
{
	const ESlateVisibility Shown = bDrawing ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed;
	const bool bFlashing = HitFlashRemaining > 0.f;
	const FLinearColor Colour = bFlashing ? HitMarkerColor : ReticleColor;
	if (ReticleRing)
	{
		// The ring is the spread while drawing, and the hit marker (a small white ring) after.
		const float Radius = bDrawing ? RingRadius : HitRingRadius;
		ReticleRing->SetVisibility(bDrawing || bFlashing ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
		FSlateBrush Brush = ReticleRing->GetBrush();
		Brush.OutlineSettings.Color = FSlateColor(Colour);
		ReticleRing->SetBrush(Brush);
		if (UCanvasPanelSlot* RingSlot = Cast<UCanvasPanelSlot>(ReticleRing->Slot))
		{
			RingSlot->SetSize(FVector2D(Radius * 2.f, Radius * 2.f));
		}
	}
	if (DrawBarBack)
	{
		DrawBarBack->SetVisibility(Shown);
	}
	if (DrawBarFill)
	{
		DrawBarFill->SetVisibility(bDrawing && DrawFraction > 0.f ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
		// Full and flashing in the perfect window: release now.
		const bool bFlashOn = bPerfectWindow && FMath::Fmod(FPlatformTime::Seconds() * 20.0, 2.0) < 1.0;
		DrawBarFill->SetBrushColor(bPerfectWindow ? (bFlashOn ? FLinearColor::White : PerfectColor) : Colour);
		if (UCanvasPanelSlot* FillSlot = Cast<UCanvasPanelSlot>(DrawBarFill->Slot))
		{
			FillSlot->SetSize(FVector2D(DrawBarWidth * DrawFraction, DrawBarHeight));
		}
	}
}

UBowComponent* UHawkeyeHudWidget::FindPawnBow() const
{
	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	return Pawn ? Pawn->FindComponentByClass<UBowComponent>() : nullptr;
}

void UHawkeyeHudWidget::PollPawnDrawState(const FGeometry& MyGeometry)
{
	UBowComponent* Bow = FindPawnBow();
	if (Bow != BoundBow)
	{
		if (BoundBow)
		{
			BoundBow->OnHit.RemoveDynamic(this, &UHawkeyeHudWidget::HandleBowHit);
		}
		BoundBow = Bow;
		if (BoundBow)
		{
			BoundBow->OnHit.AddDynamic(this, &UHawkeyeHudWidget::HandleBowHit);
		}
	}

	const APlayerController* PC = GetOwningPlayer();
	const AHawkeyeCharacter* Character = PC ? Cast<AHawkeyeCharacter>(PC->GetPawn()) : nullptr;
	if (!Bow || !Bow->IsDrawing() || !Character)
	{
		SetDrawState(false, 0.f, 0.f, false);
		return;
	}
	const float Radius = ComputeSpreadRingRadius(Bow->GetCurrentSpreadDegrees(), Character->GetCurrentFOV(),
		MyGeometry.GetLocalSize().X, ReticleSpreadDistance);
	SetDrawState(true, Bow->GetDrawFraction(), Radius, Bow->IsInPerfectWindow());
}

void UHawkeyeHudWidget::HandleBowHit(AActor* /*HitActor*/, float /*Damage*/, bool /*bHeadshot*/)
{
	FlashHitMarker();
}

void UHawkeyeHudWidget::RefreshReticle()
{
	if (ReticleDot)
	{
		ReticleDot->SetBrushColor(GetReticleColor());
		if (UCanvasPanelSlot* DotSlot = Cast<UCanvasPanelSlot>(ReticleDot->Slot))
		{
			DotSlot->SetSize(FVector2D(ReticleSizePixels, ReticleSizePixels));
		}
	}

	if (Reticle)
	{
		Reticle->SetVisibility(IsReticleVisible() ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	}
}

void UHawkeyeHudWidget::BuildGrappleMarker(UOverlay* Root)
{
	if (!WidgetTree || !Root)
	{
		return;
	}

	GrappleCanvas = WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(), TEXT("GrappleCanvas"));
	if (UOverlaySlot* CanvasSlot = Cast<UOverlaySlot>(Root->AddChild(GrappleCanvas)))
	{
		CanvasSlot->SetHorizontalAlignment(HAlign_Fill);
		CanvasSlot->SetVerticalAlignment(VAlign_Fill);
	}

	// A square whose diagonal is the marker size, outlined and not filled, turned onto its point.
	const float Side = GrappleMarkerSizePixels / UE_SQRT_2;
	FSlateBrush Brush;
	Brush.DrawAs = ESlateBrushDrawType::RoundedBox;
	Brush.TintColor = FSlateColor(FLinearColor::Transparent);
	Brush.OutlineSettings = FSlateBrushOutlineSettings(0.f, FSlateColor(GrappleMarkerColor), GrappleMarkerLineWidth);
	Brush.OutlineSettings.RoundingType = ESlateBrushRoundingType::FixedRadius;
	Brush.ImageSize = FVector2D(Side, Side);

	GrappleMarker = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("GrappleMarker"));
	GrappleMarker->SetBrush(Brush);
	GrappleMarker->SetRenderTransformPivot(FVector2D(0.5f, 0.5f));
	GrappleMarker->SetRenderTransformAngle(45.f);
	if (UCanvasPanelSlot* MarkerSlot = Cast<UCanvasPanelSlot>(GrappleCanvas->AddChild(GrappleMarker)))
	{
		MarkerSlot->SetAnchors(FAnchors(0.f, 0.f));
		MarkerSlot->SetAlignment(FVector2D(0.5f, 0.5f));
		MarkerSlot->SetAutoSize(false);
		MarkerSlot->SetSize(FVector2D(Side, Side));
	}

	GrappleHint = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("GrappleHint"));
	GrappleHint->SetColorAndOpacity(FSlateColor(GrappleMarkerColor));
	FSlateFontInfo HintFont = GrappleHint->GetFont();
	HintFont.Size = 12;
	GrappleHint->SetFont(HintFont);
	if (UCanvasPanelSlot* HintSlot = Cast<UCanvasPanelSlot>(GrappleCanvas->AddChild(GrappleHint)))
	{
		HintSlot->SetAnchors(FAnchors(0.f, 0.f));
		HintSlot->SetAlignment(FVector2D(0.5f, 0.f));
		HintSlot->SetAutoSize(true);
	}

	// The grey one: the same diamond, dim and a touch smaller, on an anchor the zip cannot reach.
	FSlateBrush Grey = Brush;
	Grey.OutlineSettings.Color = FSlateColor(GrappleUnavailableColor);
	GrappleBlockedMarker = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(), TEXT("GrappleBlockedMarker"));
	GrappleBlockedMarker->SetBrush(Grey);
	GrappleBlockedMarker->SetRenderTransformPivot(FVector2D(0.5f, 0.5f));
	GrappleBlockedMarker->SetRenderTransformAngle(45.f);
	if (UCanvasPanelSlot* BlockedSlot = Cast<UCanvasPanelSlot>(GrappleCanvas->AddChild(GrappleBlockedMarker)))
	{
		BlockedSlot->SetAnchors(FAnchors(0.f, 0.f));
		BlockedSlot->SetAlignment(FVector2D(0.5f, 0.5f));
		BlockedSlot->SetAutoSize(false);
		BlockedSlot->SetSize(FVector2D(Side, Side) * 0.8f);
	}
	GrappleBlockedMarker->SetVisibility(ESlateVisibility::Collapsed);

	GrappleBlockedText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("GrappleBlockedText"));
	GrappleBlockedText->SetColorAndOpacity(FSlateColor(GrappleUnavailableColor));
	FSlateFontInfo ReasonFont = GrappleBlockedText->GetFont();
	ReasonFont.Size = 10;
	GrappleBlockedText->SetFont(ReasonFont);
	if (UCanvasPanelSlot* ReasonSlot = Cast<UCanvasPanelSlot>(GrappleCanvas->AddChild(GrappleBlockedText)))
	{
		ReasonSlot->SetAnchors(FAnchors(0.f, 0.f));
		ReasonSlot->SetAlignment(FVector2D(0.5f, 0.f));
		ReasonSlot->SetAutoSize(true);
	}
	GrappleBlockedText->SetVisibility(ESlateVisibility::Collapsed);

	GrappleMarkerPainted = GrappleMarkerColor;
	GrappleCanvas->SetVisibility(ESlateVisibility::Collapsed);
}

FHawkeyeGrappleMarkerLook UHawkeyeHudWidget::GetGrappleMarkerLook(EGrappleTargetState State)
{
	FHawkeyeGrappleMarkerLook Look;
	switch (State)
	{
	case EGrappleTargetState::Ready:
		Look.bVisible = Look.bReady = Look.bHint = true;
		break;
	case EGrappleTargetState::NoArrows:
		Look.bVisible = Look.bHint = Look.bNoArrowsHint = true;
		break;
	case EGrappleTargetState::ArrowInFlight:
		Look.bVisible = true;
		break;
	default:
		break;
	}
	return Look;
}

bool UHawkeyeHudWidget::IsGrappleHintVisible() const
{
	return bGrappleMarkerVisible && GrappleLook.bHint;
}

void UHawkeyeHudWidget::UpdateGrappleMarker()
{
	APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	const UGrappleComponent* Grapple = Pawn ? Pawn->FindComponentByClass<UGrappleComponent>() : nullptr;
	const AGrappleAnchor* Anchor = Grapple ? Grapple->GetTargetAnchor() : nullptr;
	const EGrappleTargetState State = Grapple ? Grapple->GetTargetState() : EGrappleTargetState::None;
	GrappleLook = GetGrappleMarkerLook(State);

	FVector2D Position = FVector2D::ZeroVector;
	bGrappleMarkerVisible = Anchor && GrappleLook.bVisible
		&& UWidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition(PC, Anchor->GetMarkerLocation(), Position, false);
	if (bGrappleMarkerVisible)
	{
		GrappleMarkerPosition = Position;
	}
	const AGrappleAnchor* Blocked = Grapple ? Grapple->GetBlockedAnchor() : nullptr;
	FVector2D BlockedPosition = FVector2D::ZeroVector;
	bGrappleBlockedVisible = Blocked && Grapple->CanChain()
		&& UWidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition(PC, Blocked->GetMarkerLocation(), BlockedPosition, false);
	GrappleHintShown = !bGrappleMarkerVisible || !GrappleLook.bHint ? FText::GetEmpty()
		: (GrappleLook.bNoArrowsHint ? GrappleNoArrowsText : ApplyGamepadHint(GrappleHintText));

	if (!GrappleCanvas || !GrappleMarker || !GrappleHint)
	{
		return;
	}
	const bool bAnything = bGrappleMarkerVisible || bGrappleBlockedVisible;
	GrappleCanvas->SetVisibility(bAnything ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	if (GrappleBlockedMarker)
	{
		GrappleBlockedMarker->SetVisibility(bGrappleBlockedVisible ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
		if (UCanvasPanelSlot* BlockedSlot = bGrappleBlockedVisible ? Cast<UCanvasPanelSlot>(GrappleBlockedMarker->Slot) : nullptr)
		{
			BlockedSlot->SetPosition(BlockedPosition);
		}
	}
	if (GrappleBlockedText)
	{
		const bool bReason = bGrappleBlockedVisible && UGrappleComponent::IsDebugEnabled();
		GrappleBlockedText->SetVisibility(bReason ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
		if (bReason)
		{
			GrappleBlockedText->SetText(FText::FromString(Grapple->GetBlockedReason()));
			if (UCanvasPanelSlot* TextSlot = Cast<UCanvasPanelSlot>(GrappleBlockedText->Slot))
			{
				TextSlot->SetPosition(BlockedPosition + FVector2D(0.f, GrappleMarkerSizePixels * 0.5f + 4.f));
			}
		}
	}
	GrappleMarker->SetVisibility(bGrappleMarkerVisible ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	GrappleHint->SetVisibility(IsGrappleHintVisible() ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	if (!bGrappleMarkerVisible)
	{
		return;
	}
	const FLinearColor Colour = GrappleLook.bReady ? GrappleMarkerColor : GrappleUnavailableColor;
	if (Colour != GrappleMarkerPainted)
	{
		GrappleMarkerPainted = Colour;
		FSlateBrush Brush = GrappleMarker->GetBrush();
		Brush.OutlineSettings.Color = FSlateColor(Colour);
		GrappleMarker->SetBrush(Brush);
		GrappleHint->SetColorAndOpacity(FSlateColor(Colour));
	}
	if (UCanvasPanelSlot* MarkerSlot = Cast<UCanvasPanelSlot>(GrappleMarker->Slot))
	{
		MarkerSlot->SetPosition(Position);
	}
	if (UCanvasPanelSlot* HintSlot = Cast<UCanvasPanelSlot>(GrappleHint->Slot))
	{
		HintSlot->SetPosition(Position + FVector2D(0.f, GrappleMarkerSizePixels * 0.5f + 4.f));
	}
	GrappleHint->SetText(GrappleHintShown);
	if (UGrappleComponent::IsDebugEnabled())
	{
		GrappleHint->SetText(FText::FromString(FString::Printf(TEXT("%s  [%s, %d arrows]"), *GrappleHintShown.ToString(),
			*UEnum::GetDisplayValueAsText(State).ToString(), Grapple->GetGrappleArrows())));
		GrappleHint->SetVisibility(ESlateVisibility::HitTestInvisible);
	}
}

FLinearColor UHawkeyeHudWidget::GetReticleColor() const
{
	return HitFlashRemaining > 0.f ? HitMarkerColor : ReticleColor;
}

void UHawkeyeHudWidget::SetReticleAiming(bool bNewAiming)
{
	if (bReticleAiming == bNewAiming)
	{
		return;
	}

	bReticleAiming = bNewAiming;
	RefreshReticle();
}

void UHawkeyeHudWidget::FlashHitMarker()
{
	HitFlashRemaining = HitFlashSeconds;
	RefreshReticle();
	RefreshDrawIndicator();
}

void UHawkeyeHudWidget::PollPawnReticleState()
{
	const APlayerController* PC = GetOwningPlayer();
	const AHawkeyeCharacter* Character = PC ? Cast<AHawkeyeCharacter>(PC->GetPawn()) : nullptr;
	SetReticleAiming(Character != nullptr && Character->IsAiming());
}

FText UHawkeyeHudWidget::GetMovementDebugText() const
{
	if (!AHawkeyeCharacter::IsMovementDebugEnabled())
	{
		return FText::GetEmpty();
	}

	const APlayerController* PC = GetOwningPlayer();
	const AHawkeyeCharacter* Character = PC ? Cast<AHawkeyeCharacter>(PC->GetPawn()) : nullptr;
	return Character ? FText::FromString(Character->GetMovementDebugText()) : FText::GetEmpty();
}

void UHawkeyeHudWidget::RefreshMovementDebug()
{
	if (!DebugText)
	{
		return;
	}

	const FText Line = GetMovementDebugText();
	DebugText->SetText(Line);
	DebugText->SetVisibility(Line.IsEmpty() ? ESlateVisibility::Collapsed : ESlateVisibility::HitTestInvisible);
}

void UHawkeyeHudWidget::NativeTick(const FGeometry& MyGeometry, float DeltaSeconds)
{
	Super::NativeTick(MyGeometry, DeltaSeconds);

	PollPawnReticleState();
	PollPawnDrawState(MyGeometry);
	UpdateGrappleMarker();
	RefreshMovementDebug();
	UpdatePartnerWidgets(DeltaSeconds);
	UpdatePhoneBadge();
	UpdateComboCounter();

	if (HitFlashRemaining > 0.f)
	{
		HitFlashRemaining -= DeltaSeconds;
		if (HitFlashRemaining <= 0.f)
		{
			HitFlashRemaining = 0.f;
			RefreshReticle();
			RefreshDrawIndicator();
		}
	}
}

void UHawkeyeHudWidget::HandleWeaponHit(AActor* /*HitActor*/, float /*DamageDealt*/)
{
	FlashHitMarker();
}

void UHawkeyeHudWidget::NativeConstruct()
{
	Super::NativeConstruct();

	if (MissionCompleteText.IsEmpty())
	{
		MissionCompleteText = NSLOCTEXT("Hawkeye", "MissionComplete", "Mission complete");
	}
	if (GrappleHintText.IsEmpty())
	{
		GrappleHintText = NSLOCTEXT("Hawkeye", "GrappleHint", "Q");
	}
	if (GrappleNoArrowsText.IsEmpty())
	{
		GrappleNoArrowsText = NSLOCTEXT("Hawkeye", "GrappleNoArrows", "No grapple arrows");
	}

	BindToGame();
	RefreshObjective();
	RefreshAmmo();
	ClearPrompt();
	ApplySettings(UHawkeyeSettingsSubsystem::GetCurrentSettings(this));
}

void UHawkeyeHudWidget::NativeDestruct()
{
	UnbindFromGame();

	Super::NativeDestruct();
}

void UHawkeyeHudWidget::BindToGame()
{
	if (bBound)
	{
		return;
	}

	if (UMissionSubsystem* Missions = UMissionSubsystem::Get(this))
	{
		Missions->OnMissionStarted.AddDynamic(this, &UHawkeyeHudWidget::HandleMissionStarted);
		Missions->OnObjectiveUpdated.AddDynamic(this, &UHawkeyeHudWidget::HandleObjectiveUpdated);
		Missions->OnMissionComplete.AddDynamic(this, &UHawkeyeHudWidget::HandleMissionComplete);
	}

	if (UWeaponComponent* Weapon = FindPawnWeapon())
	{
		Weapon->OnAmmoChanged.AddDynamic(this, &UHawkeyeHudWidget::HandleAmmoChanged);
		Weapon->OnHit.AddDynamic(this, &UHawkeyeHudWidget::HandleWeaponHit);
		BoundWeapon = Weapon;
	}

	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	if (UTakedownComponent* Takedown = Pawn ? Pawn->FindComponentByClass<UTakedownComponent>() : nullptr)
	{
		Takedown->OnTakedownPerformed.AddDynamic(this, &UHawkeyeHudWidget::HandleTakedownPerformed);
		BoundTakedown = Takedown;
	}

	if (UHawkeyeSettingsSubsystem* Settings = UHawkeyeSettingsSubsystem::Get(this))
	{
		Settings->OnSettingsChanged.AddUniqueDynamic(this, &UHawkeyeHudWidget::HandleSettingsChanged);
	}

	bBound = true;
}

void UHawkeyeHudWidget::UnbindFromGame()
{
	if (!bBound)
	{
		return;
	}

	if (UMissionSubsystem* Missions = UMissionSubsystem::Get(this))
	{
		Missions->OnMissionStarted.RemoveDynamic(this, &UHawkeyeHudWidget::HandleMissionStarted);
		Missions->OnObjectiveUpdated.RemoveDynamic(this, &UHawkeyeHudWidget::HandleObjectiveUpdated);
		Missions->OnMissionComplete.RemoveDynamic(this, &UHawkeyeHudWidget::HandleMissionComplete);
	}

	if (BoundWeapon)
	{
		BoundWeapon->OnAmmoChanged.RemoveDynamic(this, &UHawkeyeHudWidget::HandleAmmoChanged);
		BoundWeapon->OnHit.RemoveDynamic(this, &UHawkeyeHudWidget::HandleWeaponHit);
		BoundWeapon = nullptr;
	}
	if (BoundBow)
	{
		BoundBow->OnHit.RemoveDynamic(this, &UHawkeyeHudWidget::HandleBowHit);
		BoundBow = nullptr;
	}

	if (BoundTakedown)
	{
		BoundTakedown->OnTakedownPerformed.RemoveDynamic(this, &UHawkeyeHudWidget::HandleTakedownPerformed);
		BoundTakedown = nullptr;
	}

	if (UHawkeyeSettingsSubsystem* Settings = UHawkeyeSettingsSubsystem::Get(this))
	{
		Settings->OnSettingsChanged.RemoveDynamic(this, &UHawkeyeHudWidget::HandleSettingsChanged);
	}

	bBound = false;
}

UWeaponComponent* UHawkeyeHudWidget::FindPawnWeapon() const
{
	const APlayerController* PC = GetOwningPlayer();
	const APawn* Pawn = PC ? PC->GetPawn() : nullptr;
	return Pawn ? Pawn->FindComponentByClass<UWeaponComponent>() : nullptr;
}

FText UHawkeyeHudWidget::FormatAmmo(int32 Magazine, int32 Reserve)
{
	return FText::FromString(FString::Printf(TEXT("%d / %d"), Magazine, Reserve));
}

FText UHawkeyeHudWidget::BuildObjectiveText() const
{
	const UMissionSubsystem* Missions = UMissionSubsystem::Get(this);
	if (!Missions)
	{
		return FText::GetEmpty();
	}

	const UMissionDefinition* Mission = Missions->GetCurrentMission();
	if (!Mission || !Mission->bShowObjectiveText)
	{
		return FText::GetEmpty();
	}

	if (const UMissionObjective* Objective = Missions->GetCurrentObjective())
	{
		// The hint goes on its own line under the title.
		return Objective->Hint.IsEmpty() ? Objective->Title
			: FText::Format(NSLOCTEXT("Hawkeye", "ObjectiveWithHint", "{0}\n{1}"), Objective->Title, Objective->Hint);
	}

	return Missions->IsMissionComplete() ? MissionCompleteText : FText::GetEmpty();
}

void UHawkeyeHudWidget::RefreshObjective()
{
	if (ObjectiveText)
	{
		ObjectiveText->SetText(BuildObjectiveText());
	}
}

void UHawkeyeHudWidget::RefreshAmmo()
{
	// The pawn can gain a weapon component (or have it enabled) partway through the level.
	UWeaponComponent* Weapon = FindPawnWeapon();
	if (Weapon && Weapon != BoundWeapon)
	{
		if (BoundWeapon)
		{
			BoundWeapon->OnAmmoChanged.RemoveDynamic(this, &UHawkeyeHudWidget::HandleAmmoChanged);
			BoundWeapon->OnHit.RemoveDynamic(this, &UHawkeyeHudWidget::HandleWeaponHit);
		}
		Weapon->OnAmmoChanged.AddDynamic(this, &UHawkeyeHudWidget::HandleAmmoChanged);
		Weapon->OnHit.AddDynamic(this, &UHawkeyeHudWidget::HandleWeaponHit);
		BoundWeapon = Weapon;
	}

	if (!AmmoText)
	{
		return;
	}

	if (!Weapon || !Weapon->HasWeapon())
	{
		AmmoText->SetText(FText::GetEmpty());
		return;
	}

	AmmoText->SetText(FormatAmmo(Weapon->CurrentAmmo, Weapon->ReserveAmmo));
}

void UHawkeyeHudWidget::SetPrompt(FText Prompt)
{
	CurrentPrompt = ApplyGamepadHint(Prompt);
	if (PromptText)
	{
		PromptText->SetText(CurrentPrompt);
	}
}

FText UHawkeyeHudWidget::ApplyGamepadHint(FText KeyboardHint) const
{
	const AHawkeyePlayerController* PC = Cast<AHawkeyePlayerController>(GetOwningPlayer());
	if (!PC || !PC->IsUsingGamepad() || KeyboardHint.IsEmpty())
	{
		return KeyboardHint;
	}

	FString Text = KeyboardHint.ToString();
	if (Text.Equals(TEXT("Q")))
	{
		// The grapple marker's bare "Q" hint; RB fires IA_Grapple on a gamepad.
		return NSLOCTEXT("Hawkeye", "GrappleHintGamepad", "RB");
	}

	// Takedown and interact share the Y face button; both prompts read the same on a pad.
	Text.ReplaceInline(TEXT("[F]"), TEXT("[Y]"));
	Text.ReplaceInline(TEXT("[E]"), TEXT("[Y]"));
	return FText::FromString(Text);
}

void UHawkeyeHudWidget::ClearPrompt()
{
	SetPrompt(FText::GetEmpty());
}

void UHawkeyeHudWidget::HandleMissionStarted(UMissionDefinition* /*Mission*/)
{
	RefreshObjective();
}

void UHawkeyeHudWidget::HandleObjectiveUpdated(UMissionObjective* /*Objective*/, int32 /*ObjectiveIndex*/)
{
	RefreshObjective();
}

void UHawkeyeHudWidget::HandleMissionComplete(UMissionDefinition* /*Mission*/)
{
	RefreshObjective();
}

void UHawkeyeHudWidget::HandleAmmoChanged(int32 /*Magazine*/, int32 /*Reserve*/)
{
	RefreshAmmo();
}

void UHawkeyeHudWidget::HandleTakedownPerformed(AActor* /*Target*/)
{
	// The guard is down; whatever prompt pointed at him is stale.
	ClearPrompt();
}

// --- Partner and switching --------------------------------------------------------------------------

void UHawkeyeHudWidget::BuildPartnerWidgets(UOverlay* Root)
{
	if (!WidgetTree || !Root)
	{
		return;
	}
	auto AddText = [this, Root](const TCHAR* Name, int32 Size, EHorizontalAlignment HAlign, const FMargin& TextPadding,
		const FLinearColor& Colour)
	{
		UTextBlock* Text = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), Name);
		FSlateFontInfo Font = Text->GetFont();
		Font.Size = Size;
		Text->SetFont(Font);
		Text->SetColorAndOpacity(FSlateColor(Colour));
		Text->SetShadowOffset(FVector2D(1.f, 1.f));
		Text->SetShadowColorAndOpacity(FLinearColor(0.f, 0.f, 0.f, 0.8f));
		Text->SetVisibility(ESlateVisibility::Collapsed);
		if (UOverlaySlot* TextSlot = Cast<UOverlaySlot>(Root->AddChild(Text)))
		{
			TextSlot->SetHorizontalAlignment(HAlign);
			TextSlot->SetVerticalAlignment(VAlign_Bottom);
			TextSlot->SetPadding(TextPadding);
		}
		return Text;
	};
	// Bottom left: who you are, and what the other one is doing. Bottom centre, over the quiver: banter.
	CharacterNameText = AddText(TEXT("CharacterName"), 22, HAlign_Left, FMargin(48.f, 0.f, 0.f, 76.f), FLinearColor::White);
	PartnerStatusText = AddText(TEXT("PartnerStatus"), 15, HAlign_Left, FMargin(48.f, 0.f, 0.f, 50.f),
		FLinearColor(0.85f, 0.8f, 0.95f, 1.f));
	// The subtitle sits in a box whose black the setting fades in; at 0 it is the bare shadowed line.
	SubtitleBox = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("SubtitleBox"));
	SubtitleBox->SetBrush(FSlateColorBrush(FLinearColor::White));
	SubtitleBox->SetBrushColor(FLinearColor(0.f, 0.f, 0.f, SubtitleBackgroundOpacity));
	SubtitleBox->SetPadding(FMargin(16.f, 6.f));
	SubtitleBox->SetVisibility(ESlateVisibility::Collapsed);
	if (UOverlaySlot* BoxSlot = Cast<UOverlaySlot>(Root->AddChild(SubtitleBox)))
	{
		BoxSlot->SetHorizontalAlignment(HAlign_Center);
		BoxSlot->SetVerticalAlignment(VAlign_Bottom);
		BoxSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 150.f));
	}
	SubtitleText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("Subtitle"));
	FSlateFontInfo SubtitleFont = SubtitleText->GetFont();
	SubtitleFont.Size = SubtitleFontSize;
	SubtitleText->SetFont(SubtitleFont);
	SubtitleText->SetColorAndOpacity(FSlateColor(FLinearColor(1.f, 0.97f, 0.88f, 1.f)));
	SubtitleText->SetShadowOffset(FVector2D(1.f, 1.f));
	SubtitleText->SetShadowColorAndOpacity(FLinearColor(0.f, 0.f, 0.f, 0.8f));
	SubtitleText->SetJustification(ETextJustify::Center);
	SubtitleText->SetAutoWrapText(true);
	SubtitleText->SetWrapTextAt(1000.f);
	SubtitleBox->SetContent(SubtitleText);

	PartnerTagCanvas = WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(), TEXT("PartnerTagCanvas"));
	if (UOverlaySlot* CanvasSlot = Cast<UOverlaySlot>(Root->AddChild(PartnerTagCanvas)))
	{
		CanvasSlot->SetHorizontalAlignment(HAlign_Fill);
		CanvasSlot->SetVerticalAlignment(VAlign_Fill);
	}
	PartnerTag = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("PartnerTag"));
	FSlateFontInfo TagFont = PartnerTag->GetFont();
	TagFont.Size = 13;
	PartnerTag->SetFont(TagFont);
	PartnerTag->SetColorAndOpacity(FSlateColor(ReticleColor));
	PartnerTag->SetShadowOffset(FVector2D(1.f, 1.f));
	PartnerTag->SetShadowColorAndOpacity(FLinearColor(0.f, 0.f, 0.f, 0.9f));
	if (UCanvasPanelSlot* TagSlot = Cast<UCanvasPanelSlot>(PartnerTagCanvas->AddChild(PartnerTag)))
	{
		TagSlot->SetAnchors(FAnchors(0.f, 0.f));
		TagSlot->SetAlignment(FVector2D(0.5f, 1.f));
		TagSlot->SetAutoSize(true);
	}
	PartnerTagCanvas->SetVisibility(ESlateVisibility::Collapsed);
}

void UHawkeyeHudWidget::SetCharacterName(FText Name)
{
	if (CharacterNameShown.EqualTo(Name))
	{
		return;
	}
	CharacterNameShown = Name;
	if (CharacterNameText)
	{
		CharacterNameText->SetText(Name);
		CharacterNameText->SetVisibility(Name.IsEmpty() ? ESlateVisibility::Collapsed : ESlateVisibility::HitTestInvisible);
	}
}

void UHawkeyeHudWidget::SetPartnerStatus(FText Status)
{
	if (PartnerStatusShown.EqualTo(Status))
	{
		return;
	}
	PartnerStatusShown = Status;
	if (PartnerStatusText)
	{
		PartnerStatusText->SetText(Status);
		PartnerStatusText->SetVisibility(Status.IsEmpty() ? ESlateVisibility::Collapsed : ESlateVisibility::HitTestInvisible);
	}
}

FText UHawkeyeHudWidget::FormatPartnerStatus(FText PartnerName, FText Status)
{
	return FText::Format(NSLOCTEXT("Hawkeye", "PartnerStatusFormat", "{0}: {1}"), PartnerName, Status);
}

void UHawkeyeHudWidget::ShowSubtitle(FText Speaker, FText Line, float Seconds)
{
	SubtitleShown = FText::Format(NSLOCTEXT("Hawkeye", "SubtitleFormat", "{0}: {1}"), Speaker, Line);
	SubtitleRemaining = FMath::Max(Seconds, 0.f);
	if (SubtitleText)
	{
		SubtitleText->SetText(SubtitleShown);
	}
	if (SubtitleBox)
	{
		SubtitleBox->SetVisibility(SubtitleRemaining > 0.f ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	}
}

void UHawkeyeHudWidget::RebindToPawn()
{
	UnbindFromGame();
	BindToGame();
	RefreshAmmo();
	if (Hotbar)
	{
		Hotbar->BindToOwningPawn();
	}
	const APlayerController* PC = GetOwningPlayer();
	if (const AHawkeyeCharacter* Character = PC ? Cast<AHawkeyeCharacter>(PC->GetPawn()) : nullptr)
	{
		SetCharacterName(Character->GetCharacterName());
	}
}

void UHawkeyeHudWidget::UpdatePartnerWidgets(float DeltaSeconds)
{
	if (SubtitleRemaining > 0.f)
	{
		SubtitleRemaining -= DeltaSeconds;
		if (SubtitleRemaining <= 0.f && SubtitleBox)
		{
			SubtitleRemaining = 0.f;
			SubtitleBox->SetVisibility(ESlateVisibility::Collapsed);
		}
	}

	APlayerController* PC = GetOwningPlayer();
	const AHawkeyeCharacter* Lead = PC ? Cast<AHawkeyeCharacter>(PC->GetPawn()) : nullptr;
	UWorld* World = GetWorld();
	if (Lead)
	{
		SetCharacterName(Lead->GetCharacterName());
	}

	const AHawkeyePartnerController* PartnerBrain = nullptr;
	if (World)
	{
		for (TActorIterator<AHawkeyePartnerController> It(World); It; ++It)
		{
			if (It->GetPawn() && (!PartnerBrain || It->GetLeader() == Lead))
			{
				PartnerBrain = *It;
			}
		}
	}
	const AHawkeyeCharacter* Partner = PartnerBrain ? PartnerBrain->GetPartner() : nullptr;
	SetPartnerStatus(Partner ? FormatPartnerStatus(Partner->GetCharacterName(), PartnerBrain->GetStatusText()) : FText::GetEmpty());

	FVector2D TagPosition = FVector2D::ZeroVector;
	const float Distance = (Partner && Lead) ? FVector::Dist(Partner->GetActorLocation(), Lead->GetActorLocation()) : 0.f;
	bPartnerTagVisible = Partner && Lead && ShouldShowPartnerTag(Distance, PartnerTagMinDistance)
		&& UWidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition(
			PC, Partner->GetActorLocation() + FVector(0.f, 0.f, PartnerTagHeight), TagPosition, false);
	if (!PartnerTagCanvas || !PartnerTag)
	{
		return;
	}
	PartnerTagCanvas->SetVisibility(bPartnerTagVisible ? ESlateVisibility::HitTestInvisible : ESlateVisibility::Collapsed);
	if (bPartnerTagVisible)
	{
		PartnerTag->SetText(FText::FromString(Partner->GetCharacterName().ToString().ToUpper()));
		if (UCanvasPanelSlot* TagSlot = Cast<UCanvasPanelSlot>(PartnerTag->Slot))
		{
			TagSlot->SetPosition(TagPosition);
		}
	}
}

// --- Settings ---------------------------------------------------------------------------------------

void UHawkeyeHudWidget::HandleSettingsChanged(FHawkeyeSettings Settings)
{
	ApplySettings(Settings);
}

void UHawkeyeHudWidget::ApplySettings(const FHawkeyeSettings& Settings)
{
	ApplyPalette(Settings.ColorPalette);

	SubtitleFontSize = UHawkeyeAccessibility::GetSubtitleFontSize(Settings.SubtitleSize);
	SubtitleBackgroundOpacity = FMath::Clamp(Settings.SubtitleBackgroundOpacity, 0.f, 1.f);
	if (SubtitleText)
	{
		FSlateFontInfo Font = SubtitleText->GetFont();
		Font.Size = SubtitleFontSize;
		SubtitleText->SetFont(Font);
	}
	if (SubtitleBox)
	{
		SubtitleBox->SetBrushColor(FLinearColor(0.f, 0.f, 0.f, SubtitleBackgroundOpacity));
	}

	ApplyHudScale(UHawkeyeSettingsSubsystem::ClampHudScale(Settings.HudScale));
}

void UHawkeyeHudWidget::ApplyPalette(EHawkeyeColorPalette Palette)
{
	if (!bDesignColorsKept)
	{
		DesignReticleColor = ReticleColor;
		DesignGrappleColor = GrappleMarkerColor;
		DesignComboColor = ComboColor;
		DesignComboBonusColor = ComboBonusColor;
		bDesignColorsKept = true;
	}
	PaletteShown = Palette;
	ActivePalette = UHawkeyeAccessibility::GetPalette(Palette);
	const bool bDesign = Palette == EHawkeyeColorPalette::Default;
	ReticleColor = bDesign ? DesignReticleColor : ActivePalette.Purple;
	GrappleMarkerColor = bDesign ? DesignGrappleColor : ActivePalette.Green;
	ComboColor = bDesign ? DesignComboColor : ActivePalette.Cream;
	ComboBonusColor = bDesign ? DesignComboBonusColor : ActivePalette.Purple;
	if (bDesign)
	{
		ActivePalette.Purple = ReticleColor;
		ActivePalette.Green = GrappleMarkerColor;
	}

	RefreshReticle();
	RefreshDrawIndicator();
	if (GrappleMarker)
	{
		FSlateBrush Brush = GrappleMarker->GetBrush();
		Brush.OutlineSettings.Color = FSlateColor(GrappleMarkerColor);
		GrappleMarker->SetBrush(Brush);
		GrappleMarkerPainted = GrappleMarkerColor;
	}
	if (GrappleHint)
	{
		GrappleHint->SetColorAndOpacity(FSlateColor(GrappleMarkerColor));
	}
	if (PhoneBadgeText)
	{
		PhoneBadgeText->SetColorAndOpacity(FSlateColor(ReticleColor));
	}
	if (PartnerTag)
	{
		PartnerTag->SetColorAndOpacity(FSlateColor(ReticleColor));
	}
	if (ObjectiveMarker)
	{
		ObjectiveMarker->SetAccentColors(ActivePalette.Cream, ReticleColor, bDesign);
	}
	if (ThugOverhead)
	{
		ThugOverhead->SetAccentColors(ActivePalette.Cream, ActivePalette.HealthBar, bDesign);
	}
	if (Hotbar)
	{
		Hotbar->SetAccentColor(ReticleColor, bDesign);
	}
	// Repaint the badge and the counter with the new colours on the next tick.
	PhoneBadgeCount = -1;
	ShownComboCount = -1;
	UpdatePhoneBadge();
	UpdateComboCounter();
}

void UHawkeyeHudWidget::ApplyHudScale(float Scale)
{
	HudScale = Scale;
	const FVector2D Size(Scale, Scale);
	auto ScaleAbout = [&Size](UWidget* Part, const FVector2D& Pivot)
	{
		if (Part)
		{
			Part->SetRenderTransformPivot(Pivot);
			Part->SetRenderScale(Size);
		}
	};
	// Each part grows from the corner or edge it is pinned to, so nothing slides off the screen.
	ScaleAbout(ObjectiveText, FVector2D(0.f, 0.f));
	ScaleAbout(DebugText, FVector2D(0.f, 0.f));
	ScaleAbout(AmmoText, FVector2D(1.f, 1.f));
	ScaleAbout(PromptText, FVector2D(0.5f, 0.5f));
	ScaleAbout(CharacterNameText, FVector2D(0.f, 1.f));
	ScaleAbout(PartnerStatusText, FVector2D(0.f, 1.f));
	ScaleAbout(PhoneBadge, FVector2D(1.f, 1.f));
	ScaleAbout(ComboText, FVector2D(1.f, 0.5f));
	ScaleAbout(ChallengePanel, FVector2D(1.f, 0.f));
	ScaleAbout(CrimePanel, FVector2D(1.f, 0.f));
	ScaleAbout(Hotbar, FVector2D(0.5f, 1.f));
	ScaleAbout(GrappleMarker, FVector2D(0.5f, 0.5f));
	ScaleAbout(GrappleBlockedMarker, FVector2D(0.5f, 0.5f));
	if (ObjectiveMarker)
	{
		ObjectiveMarker->SetHudScale(Scale);
	}
}

float UHawkeyeHudWidget::GetHotbarRenderScale() const
{
	return Hotbar ? Hotbar->GetRenderTransform().Scale.X : 1.f;
}
