// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "HawkeyeHotbarWidget.generated.h"

class UBorder;
class UHorizontalBox;
class UInventoryComponent;
class UTextBlock;

/**
 * The quiver along the bottom of the screen: six boxes, one per slot, each with its number key,
 * the arrow's short name and its count ("30" for standard arrows, "6/6" for a trick arrow, which
 * shows its cap). The active slot is drawn bright, an empty slot is dimmed.
 *
 * Built in C++ like the rest of the HUD, because WBP_Hotbar is generated by a script and has
 * no designer layout. UHawkeyeHudWidget creates one and parents it into its own overlay.
 *
 * Every piece of state is a pure function of the bound inventory, so a test can bind one and
 * read the labels back without building Slate. Slots are 1..6.
 */
UCLASS(Blueprintable, BlueprintType)
class HAWKEYE_API UHawkeyeHotbarWidget : public UUserWidget
{
	GENERATED_BODY()

public:
	/** Binds to Inventory's change delegates and repaints. Passing null unbinds. */
	UFUNCTION(BlueprintCallable, Category = "HUD|Hotbar")
	void BindToInventory(UInventoryComponent* Inventory);

	/** Finds the owning pawn's inventory and binds to it. Called from NativeConstruct. */
	UFUNCTION(BlueprintCallable, Category = "HUD|Hotbar")
	void BindToOwningPawn();

	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	UInventoryComponent* GetBoundInventory() const { return BoundInventory; }

	/** Repaints every slot box from the bound inventory. */
	UFUNCTION(BlueprintCallable, Category = "HUD|Hotbar")
	void RefreshSlots();

	/** Active quiver slot of the bound inventory, or 1 when nothing is bound. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	int32 GetActiveSlot() const;

	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	bool IsSlotActive(int32 QuiverSlot) const;

	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	bool IsSlotEmpty(int32 QuiverSlot) const;

	/** "1".."6": the key that selects the slot. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	static FText GetSlotKeyText(int32 QuiverSlot);

	/** The arrow's short name, or "--" for an empty slot. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	FText GetSlotNameText(int32 QuiverSlot) const;

	/** "30" for slot 1 (standard arrows are plentiful), "count/cap" for trick arrows, empty for an empty slot. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	FText GetSlotCountText(int32 QuiverSlot) const;

	/** The colour a slot box is drawn in right now: active, filled or dimmed empty. */
	UFUNCTION(BlueprintPure, Category = "HUD|Hotbar")
	FLinearColor GetSlotColor(int32 QuiverSlot) const;

protected:
	//~ Begin UUserWidget interface
	virtual TSharedRef<SWidget> RebuildWidget() override;
	virtual void NativeConstruct() override;
	virtual void NativeDestruct() override;
	//~ End UUserWidget interface

	UFUNCTION()
	void HandleInventoryChanged();

	UFUNCTION()
	void HandleActiveSlotChanged(int32 OldSlot, int32 NewSlot);

	/** Row the slot boxes live in. Built in RebuildWidget. */
	UPROPERTY(BlueprintReadOnly, Category = "HUD|Hotbar", meta = (BindWidgetOptional))
	TObjectPtr<UHorizontalBox> SlotRow = nullptr;

	UPROPERTY(Transient, BlueprintReadOnly, Category = "HUD|Hotbar")
	TArray<TObjectPtr<UBorder>> SlotBoxes;

	UPROPERTY(Transient, BlueprintReadOnly, Category = "HUD|Hotbar")
	TArray<TObjectPtr<UTextBlock>> SlotKeyTexts;

	UPROPERTY(Transient, BlueprintReadOnly, Category = "HUD|Hotbar")
	TArray<TObjectPtr<UTextBlock>> SlotNameTexts;

	UPROPERTY(Transient, BlueprintReadOnly, Category = "HUD|Hotbar")
	TArray<TObjectPtr<UTextBlock>> SlotCountTexts;

	/** The nocked slot: the one bright box on the bar. Kate purple. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "HUD|Hotbar")
	FLinearColor ActiveSlotColor = FLinearColor(0.42f, 0.16f, 0.72f, 0.9f);

	/** A slot that holds arrows but is not nocked. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "HUD|Hotbar")
	FLinearColor FilledSlotColor = FLinearColor(0.f, 0.f, 0.f, 0.55f);

	/** Width every slot box is at least, so the six of them line up. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "HUD|Hotbar", meta = (ClampMin = "1.0"))
	float SlotWidthPixels = 76.f;

	/** A slot with nothing in it. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category = "HUD|Hotbar")
	FLinearColor EmptySlotColor = FLinearColor(0.f, 0.f, 0.f, 0.22f);

	UPROPERTY(Transient)
	TObjectPtr<UInventoryComponent> BoundInventory = nullptr;
};
