// Copyright Epic Games, Inc. All Rights Reserved.

#include "UI/HawkeyeSettingsWidget.h"

#include "Blueprint/WidgetTree.h"
#include "Brushes/SlateColorBrush.h"
#include "Components/Border.h"
#include "Components/Button.h"
#include "Components/ButtonSlot.h"
#include "Components/CheckBox.h"
#include "Components/HorizontalBox.h"
#include "Components/HorizontalBoxSlot.h"
#include "Components/Overlay.h"
#include "Components/OverlaySlot.h"
#include "Components/SizeBox.h"
#include "Components/SizeBoxSlot.h"
#include "Components/Slider.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "Audio/HawkeyeAudioSubsystem.h"
#include "Settings/HawkeyeSettingsSubsystem.h"

namespace HawkeyeSettingsWidgetLayout
{
	/** Step is 0.01, so the number under the slider never shows a third decimal. */
	static constexpr float SliderStep = 0.01f;

	static constexpr float RowWidth = 760.f;
	static constexpr float LabelWidth = 300.f;
	static constexpr float ValueWidth = 90.f;
	static constexpr float SliderHeight = 28.f;

	/** Grows a text block's default font without needing a font asset of our own. */
	static void SetFontSize(UTextBlock* Text, int32 Size)
	{
		if (!Text)
		{
			return;
		}
		FSlateFontInfo Font = Text->GetFont();
		Font.Size = Size;
		Text->SetFont(Font);
	}
}

void UHawkeyeSettingsWidget::ApplyDefaultLabels()
{
	if (TitleLabel.IsEmpty())
	{
		TitleLabel = NSLOCTEXT("Hawkeye", "SettingsTitle", "Settings");
	}
	if (SensitivityLabel.IsEmpty())
	{
		SensitivityLabel = NSLOCTEXT("Hawkeye", "SettingsSensitivity", "Mouse sensitivity");
	}
	if (StickSensitivityLabel.IsEmpty())
	{
		StickSensitivityLabel = NSLOCTEXT("Hawkeye", "SettingsStickSensitivity", "Controller sensitivity");
	}
	if (BackLabel.IsEmpty())
	{
		BackLabel = NSLOCTEXT("Hawkeye", "SettingsBack", "Back");
	}
	if (InvertMouseYLabel.IsEmpty())
	{
		InvertMouseYLabel = NSLOCTEXT("Hawkeye", "SettingsInvertMouseY", "Invert mouse Y");
	}
	if (InvertStickYLabel.IsEmpty())
	{
		InvertStickYLabel = NSLOCTEXT("Hawkeye", "SettingsInvertStickY", "Invert controller Y");
	}
	if (MasterVolumeLabel.IsEmpty())
	{
		MasterVolumeLabel = NSLOCTEXT("Hawkeye", "SettingsMasterVolume", "Master volume");
	}
	if (SfxVolumeLabel.IsEmpty())
	{
		SfxVolumeLabel = NSLOCTEXT("Hawkeye", "SettingsSfxVolume", "Sound effects");
	}
	if (AmbientVolumeLabel.IsEmpty())
	{
		AmbientVolumeLabel = NSLOCTEXT("Hawkeye", "SettingsAmbientVolume", "Ambience");
	}
}

TSharedRef<SWidget> UHawkeyeSettingsWidget::RebuildWidget()
{
	using namespace HawkeyeSettingsWidgetLayout;

	// WBP_Settings is generated by a script and has no designer layout, so build one here.
	if (WidgetTree && !WidgetTree->RootWidget)
	{
		ApplyDefaultLabels();

		UOverlay* Root = WidgetTree->ConstructWidget<UOverlay>(UOverlay::StaticClass(), TEXT("SettingsRoot"));
		WidgetTree->RootWidget = Root;

		// Darker than the pause menu's dimmer: the settings screen replaces it rather than
		// sitting on top, so the frozen game should read as further away still.
		//
		// The brush is set explicitly because UBorder's default Background is an Image brush with
		// no resource, which draws nothing however it is tinted - so SetBrushColor alone leaves the
		// live game at full brightness behind the text.
		UBorder* Dimmer = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass(), TEXT("Dimmer"));
		Dimmer->SetBrush(FSlateColorBrush(FLinearColor::White));
		Dimmer->SetBrushColor(FLinearColor(0.f, 0.f, 0.f, 0.75f));
		if (UOverlaySlot* DimmerSlot = Cast<UOverlaySlot>(Root->AddChild(Dimmer)))
		{
			DimmerSlot->SetHorizontalAlignment(HAlign_Fill);
			DimmerSlot->SetVerticalAlignment(VAlign_Fill);
		}

		OptionStack = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(), TEXT("OptionStack"));
		if (UOverlaySlot* StackSlot = Cast<UOverlaySlot>(Root->AddChild(OptionStack)))
		{
			StackSlot->SetHorizontalAlignment(HAlign_Center);
			StackSlot->SetVerticalAlignment(VAlign_Center);
		}

		if (!TitleText)
		{
			TitleText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("TitleText"));
		}
		TitleText->SetText(TitleLabel);
		SetFontSize(TitleText, 36);
		if (UVerticalBoxSlot* TitleSlot = Cast<UVerticalBoxSlot>(OptionStack->AddChild(TitleText)))
		{
			TitleSlot->SetHorizontalAlignment(HAlign_Center);
			TitleSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 40.f));
		}

		// --- The one option: label, slider, value, on a single fixed-width row ---------------
		USizeBox* RowBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("SensitivityRowBox"));
		RowBox->SetWidthOverride(RowWidth);
		if (UVerticalBoxSlot* RowSlot = Cast<UVerticalBoxSlot>(OptionStack->AddChild(RowBox)))
		{
			RowSlot->SetHorizontalAlignment(HAlign_Center);
			RowSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 40.f));
		}

		UHorizontalBox* Row =
			WidgetTree->ConstructWidget<UHorizontalBox>(UHorizontalBox::StaticClass(), TEXT("SensitivityRow"));
		if (USizeBoxSlot* RowInner = Cast<USizeBoxSlot>(RowBox->AddChild(Row)))
		{
			RowInner->SetHorizontalAlignment(HAlign_Fill);
			RowInner->SetVerticalAlignment(VAlign_Center);
		}

		if (!SensitivityLabelText)
		{
			SensitivityLabelText =
				WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("SensitivityLabelText"));
		}
		SensitivityLabelText->SetText(SensitivityLabel);
		SetFontSize(SensitivityLabelText, 20);

		USizeBox* LabelBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("LabelBox"));
		LabelBox->SetWidthOverride(LabelWidth);
		if (USizeBoxSlot* LabelInner = Cast<USizeBoxSlot>(LabelBox->AddChild(SensitivityLabelText)))
		{
			LabelInner->SetHorizontalAlignment(HAlign_Left);
			LabelInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* LabelSlot = Cast<UHorizontalBoxSlot>(Row->AddChild(LabelBox)))
		{
			LabelSlot->SetVerticalAlignment(VAlign_Center);
		}

		if (!SensitivitySlider)
		{
			SensitivitySlider =
				WidgetTree->ConstructWidget<USlider>(USlider::StaticClass(), TEXT("SensitivitySlider"));
		}

		USizeBox* SliderBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("SliderBox"));
		SliderBox->SetHeightOverride(SliderHeight);
		if (USizeBoxSlot* SliderInner = Cast<USizeBoxSlot>(SliderBox->AddChild(SensitivitySlider)))
		{
			SliderInner->SetHorizontalAlignment(HAlign_Fill);
			SliderInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* SliderSlot = Cast<UHorizontalBoxSlot>(Row->AddChild(SliderBox)))
		{
			SliderSlot->SetSize(FSlateChildSize(ESlateSizeRule::Fill));
			SliderSlot->SetVerticalAlignment(VAlign_Center);
			SliderSlot->SetPadding(FMargin(0.f, 0.f, 24.f, 0.f));
		}

		if (!SensitivityValueText)
		{
			SensitivityValueText =
				WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("SensitivityValueText"));
		}
		SetFontSize(SensitivityValueText, 20);

		USizeBox* ValueBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("ValueBox"));
		ValueBox->SetWidthOverride(ValueWidth);
		if (USizeBoxSlot* ValueInner = Cast<USizeBoxSlot>(ValueBox->AddChild(SensitivityValueText)))
		{
			ValueInner->SetHorizontalAlignment(HAlign_Right);
			ValueInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* ValueSlot = Cast<UHorizontalBoxSlot>(Row->AddChild(ValueBox)))
		{
			ValueSlot->SetVerticalAlignment(VAlign_Center);
		}

		// --- Second option: controller sensitivity, same row shape as the mouse one -------------
		USizeBox* StickRowBox =
			WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("StickSensitivityRowBox"));
		StickRowBox->SetWidthOverride(RowWidth);
		if (UVerticalBoxSlot* StickRowSlot = Cast<UVerticalBoxSlot>(OptionStack->AddChild(StickRowBox)))
		{
			StickRowSlot->SetHorizontalAlignment(HAlign_Center);
			StickRowSlot->SetPadding(FMargin(0.f, 0.f, 0.f, 40.f));
		}

		UHorizontalBox* StickRow =
			WidgetTree->ConstructWidget<UHorizontalBox>(UHorizontalBox::StaticClass(), TEXT("StickSensitivityRow"));
		if (USizeBoxSlot* StickRowInner = Cast<USizeBoxSlot>(StickRowBox->AddChild(StickRow)))
		{
			StickRowInner->SetHorizontalAlignment(HAlign_Fill);
			StickRowInner->SetVerticalAlignment(VAlign_Center);
		}

		if (!StickSensitivityLabelText)
		{
			StickSensitivityLabelText =
				WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("StickSensitivityLabelText"));
		}
		StickSensitivityLabelText->SetText(StickSensitivityLabel);
		SetFontSize(StickSensitivityLabelText, 20);

		USizeBox* StickLabelBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("StickLabelBox"));
		StickLabelBox->SetWidthOverride(LabelWidth);
		if (USizeBoxSlot* StickLabelInner = Cast<USizeBoxSlot>(StickLabelBox->AddChild(StickSensitivityLabelText)))
		{
			StickLabelInner->SetHorizontalAlignment(HAlign_Left);
			StickLabelInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* StickLabelSlot = Cast<UHorizontalBoxSlot>(StickRow->AddChild(StickLabelBox)))
		{
			StickLabelSlot->SetVerticalAlignment(VAlign_Center);
		}

		if (!StickSensitivitySlider)
		{
			StickSensitivitySlider =
				WidgetTree->ConstructWidget<USlider>(USlider::StaticClass(), TEXT("StickSensitivitySlider"));
		}

		USizeBox* StickSliderBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("StickSliderBox"));
		StickSliderBox->SetHeightOverride(SliderHeight);
		if (USizeBoxSlot* StickSliderInner = Cast<USizeBoxSlot>(StickSliderBox->AddChild(StickSensitivitySlider)))
		{
			StickSliderInner->SetHorizontalAlignment(HAlign_Fill);
			StickSliderInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* StickSliderSlot = Cast<UHorizontalBoxSlot>(StickRow->AddChild(StickSliderBox)))
		{
			StickSliderSlot->SetSize(FSlateChildSize(ESlateSizeRule::Fill));
			StickSliderSlot->SetVerticalAlignment(VAlign_Center);
			StickSliderSlot->SetPadding(FMargin(0.f, 0.f, 24.f, 0.f));
		}

		if (!StickSensitivityValueText)
		{
			StickSensitivityValueText =
				WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("StickSensitivityValueText"));
		}
		SetFontSize(StickSensitivityValueText, 20);

		USizeBox* StickValueBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), TEXT("StickValueBox"));
		StickValueBox->SetWidthOverride(ValueWidth);
		if (USizeBoxSlot* StickValueInner = Cast<USizeBoxSlot>(StickValueBox->AddChild(StickSensitivityValueText)))
		{
			StickValueInner->SetHorizontalAlignment(HAlign_Right);
			StickValueInner->SetVerticalAlignment(VAlign_Center);
		}
		if (UHorizontalBoxSlot* StickValueSlot = Cast<UHorizontalBoxSlot>(StickRow->AddChild(StickValueBox)))
		{
			StickValueSlot->SetVerticalAlignment(VAlign_Center);
		}

		// --- Invert Y checkboxes, one row each, same label column as the sliders above -----------
		auto BuildCheckboxRow = [&](const FText& Label, TObjectPtr<UCheckBox>& OutCheckBox,
			TObjectPtr<UTextBlock>& OutLabelText, const TCHAR* BaseName)
		{
			USizeBox* RowBoxLocal = WidgetTree->ConstructWidget<USizeBox>(
				USizeBox::StaticClass(), *(FString(BaseName) + TEXT("RowBox")));
			RowBoxLocal->SetWidthOverride(RowWidth);
			if (UVerticalBoxSlot* RowSlotLocal = Cast<UVerticalBoxSlot>(OptionStack->AddChild(RowBoxLocal)))
			{
				RowSlotLocal->SetHorizontalAlignment(HAlign_Center);
				RowSlotLocal->SetPadding(FMargin(0.f, 0.f, 0.f, 40.f));
			}

			UHorizontalBox* RowLocal = WidgetTree->ConstructWidget<UHorizontalBox>(
				UHorizontalBox::StaticClass(), *(FString(BaseName) + TEXT("Row")));
			if (USizeBoxSlot* RowInnerLocal = Cast<USizeBoxSlot>(RowBoxLocal->AddChild(RowLocal)))
			{
				RowInnerLocal->SetHorizontalAlignment(HAlign_Fill);
				RowInnerLocal->SetVerticalAlignment(VAlign_Center);
			}

			if (!OutLabelText)
			{
				OutLabelText = WidgetTree->ConstructWidget<UTextBlock>(
					UTextBlock::StaticClass(), *(FString(BaseName) + TEXT("LabelText")));
			}
			OutLabelText->SetText(Label);
			SetFontSize(OutLabelText, 20);

			USizeBox* LabelBoxLocal =
				WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), *(FString(BaseName) + TEXT("LabelBox")));
			LabelBoxLocal->SetWidthOverride(LabelWidth);
			if (USizeBoxSlot* LabelInnerLocal = Cast<USizeBoxSlot>(LabelBoxLocal->AddChild(OutLabelText)))
			{
				LabelInnerLocal->SetHorizontalAlignment(HAlign_Left);
				LabelInnerLocal->SetVerticalAlignment(VAlign_Center);
			}
			if (UHorizontalBoxSlot* LabelSlotLocal = Cast<UHorizontalBoxSlot>(RowLocal->AddChild(LabelBoxLocal)))
			{
				LabelSlotLocal->SetVerticalAlignment(VAlign_Center);
			}

			if (!OutCheckBox)
			{
				OutCheckBox = WidgetTree->ConstructWidget<UCheckBox>(
					UCheckBox::StaticClass(), *(FString(BaseName) + TEXT("CheckBox")));
			}
			if (UHorizontalBoxSlot* CheckSlotLocal = Cast<UHorizontalBoxSlot>(RowLocal->AddChild(OutCheckBox)))
			{
				CheckSlotLocal->SetVerticalAlignment(VAlign_Center);
			}
		};

		BuildCheckboxRow(InvertMouseYLabel, InvertMouseYCheckBox, InvertMouseYLabelText, TEXT("InvertMouseY"));
		BuildCheckboxRow(InvertStickYLabel, InvertStickYCheckBox, InvertStickYLabelText, TEXT("InvertStickY"));

		// --- Volume sliders: the sensitivity rows' shape, a little tighter so all fit at 720p -----
		auto BuildVolumeRow = [&](const FText& Label, TObjectPtr<USlider>& OutSlider, TObjectPtr<UTextBlock>& OutValue,
			TObjectPtr<UTextBlock>& OutLabelText, const TCHAR* BaseName)
		{
			const FString Base(BaseName);
			USizeBox* RowBoxLocal = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), *(Base + TEXT("RowBox")));
			RowBoxLocal->SetWidthOverride(RowWidth);
			if (UVerticalBoxSlot* RowSlotLocal = Cast<UVerticalBoxSlot>(OptionStack->AddChild(RowBoxLocal)))
			{
				RowSlotLocal->SetHorizontalAlignment(HAlign_Center);
				RowSlotLocal->SetPadding(FMargin(0.f, 0.f, 0.f, 24.f));
			}
			UHorizontalBox* RowLocal =
				WidgetTree->ConstructWidget<UHorizontalBox>(UHorizontalBox::StaticClass(), *(Base + TEXT("Row")));
			if (USizeBoxSlot* RowInnerLocal = Cast<USizeBoxSlot>(RowBoxLocal->AddChild(RowLocal)))
			{
				RowInnerLocal->SetHorizontalAlignment(HAlign_Fill);
				RowInnerLocal->SetVerticalAlignment(VAlign_Center);
			}

			if (!OutLabelText)
			{
				OutLabelText =
					WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), *(Base + TEXT("LabelText")));
			}
			OutLabelText->SetText(Label);
			SetFontSize(OutLabelText, 20);
			USizeBox* LabelBoxLocal =
				WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), *(Base + TEXT("LabelBox")));
			LabelBoxLocal->SetWidthOverride(LabelWidth);
			if (USizeBoxSlot* LabelInnerLocal = Cast<USizeBoxSlot>(LabelBoxLocal->AddChild(OutLabelText)))
			{
				LabelInnerLocal->SetHorizontalAlignment(HAlign_Left);
				LabelInnerLocal->SetVerticalAlignment(VAlign_Center);
			}
			if (UHorizontalBoxSlot* LabelSlotLocal = Cast<UHorizontalBoxSlot>(RowLocal->AddChild(LabelBoxLocal)))
			{
				LabelSlotLocal->SetVerticalAlignment(VAlign_Center);
			}

			if (!OutSlider)
			{
				OutSlider = WidgetTree->ConstructWidget<USlider>(USlider::StaticClass(), *(Base + TEXT("Slider")));
			}
			USizeBox* SliderBoxLocal =
				WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), *(Base + TEXT("SliderBox")));
			SliderBoxLocal->SetHeightOverride(SliderHeight);
			if (USizeBoxSlot* SliderInnerLocal = Cast<USizeBoxSlot>(SliderBoxLocal->AddChild(OutSlider)))
			{
				SliderInnerLocal->SetHorizontalAlignment(HAlign_Fill);
				SliderInnerLocal->SetVerticalAlignment(VAlign_Center);
			}
			if (UHorizontalBoxSlot* SliderSlotLocal = Cast<UHorizontalBoxSlot>(RowLocal->AddChild(SliderBoxLocal)))
			{
				SliderSlotLocal->SetSize(FSlateChildSize(ESlateSizeRule::Fill));
				SliderSlotLocal->SetVerticalAlignment(VAlign_Center);
				SliderSlotLocal->SetPadding(FMargin(0.f, 0.f, 24.f, 0.f));
			}

			if (!OutValue)
			{
				OutValue = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), *(Base + TEXT("ValueText")));
			}
			SetFontSize(OutValue, 20);
			USizeBox* ValueBoxLocal =
				WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass(), *(Base + TEXT("ValueBox")));
			ValueBoxLocal->SetWidthOverride(ValueWidth);
			if (USizeBoxSlot* ValueInnerLocal = Cast<USizeBoxSlot>(ValueBoxLocal->AddChild(OutValue)))
			{
				ValueInnerLocal->SetHorizontalAlignment(HAlign_Right);
				ValueInnerLocal->SetVerticalAlignment(VAlign_Center);
			}
			if (UHorizontalBoxSlot* ValueSlotLocal = Cast<UHorizontalBoxSlot>(RowLocal->AddChild(ValueBoxLocal)))
			{
				ValueSlotLocal->SetVerticalAlignment(VAlign_Center);
			}
		};

		BuildVolumeRow(MasterVolumeLabel, MasterVolumeSlider, MasterVolumeValueText, MasterVolumeLabelText,
			TEXT("MasterVolume"));
		BuildVolumeRow(SfxVolumeLabel, SfxVolumeSlider, SfxVolumeValueText, SfxVolumeLabelText, TEXT("SfxVolume"));
		BuildVolumeRow(AmbientVolumeLabel, AmbientVolumeSlider, AmbientVolumeValueText, AmbientVolumeLabelText,
			TEXT("AmbientVolume"));

		// --- Back -----------------------------------------------------------------------------
		if (!BackButton)
		{
			BackButton = WidgetTree->ConstructWidget<UButton>(UButton::StaticClass(), TEXT("BackButton"));
		}

		UTextBlock* BackText =
			WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(), TEXT("BackButtonLabel"));
		BackText->SetText(BackLabel);
		SetFontSize(BackText, 20);
		if (UButtonSlot* BackTextSlot = Cast<UButtonSlot>(BackButton->AddChild(BackText)))
		{
			BackTextSlot->SetHorizontalAlignment(HAlign_Center);
			BackTextSlot->SetPadding(FMargin(48.f, 12.f));
		}
		if (UVerticalBoxSlot* BackSlot = Cast<UVerticalBoxSlot>(OptionStack->AddChild(BackButton)))
		{
			BackSlot->SetHorizontalAlignment(HAlign_Center);
		}
	}

	return Super::RebuildWidget();
}

void UHawkeyeSettingsWidget::NativeConstruct()
{
	Super::NativeConstruct();

	ApplyDefaultLabels();

	if (SensitivitySlider)
	{
		// The range is the subsystem's, not the designer's: a slider that can ask for a value
		// the subsystem clamps away would snap back under the player's thumb.
		SensitivitySlider->SetMinValue(UHawkeyeSettingsSubsystem::MinLookSensitivity);
		SensitivitySlider->SetMaxValue(UHawkeyeSettingsSubsystem::MaxLookSensitivity);
		SensitivitySlider->SetStepSize(HawkeyeSettingsWidgetLayout::SliderStep);
	}
	if (StickSensitivitySlider)
	{
		StickSensitivitySlider->SetMinValue(UHawkeyeSettingsSubsystem::MinStickSensitivity);
		StickSensitivitySlider->SetMaxValue(UHawkeyeSettingsSubsystem::MaxStickSensitivity);
		StickSensitivitySlider->SetStepSize(HawkeyeSettingsWidgetLayout::SliderStep);
	}

	for (USlider* Volume : { MasterVolumeSlider.Get(), SfxVolumeSlider.Get(), AmbientVolumeSlider.Get() })
	{
		if (Volume)
		{
			Volume->SetMinValue(0.f);
			Volume->SetMaxValue(1.f);
			Volume->SetStepSize(HawkeyeSettingsWidgetLayout::SliderStep);
		}
	}

	if (!bBound)
	{
		if (MasterVolumeSlider)
		{
			MasterVolumeSlider->OnValueChanged.AddDynamic(this, &UHawkeyeSettingsWidget::HandleMasterVolumeChanged);
		}
		if (SfxVolumeSlider)
		{
			SfxVolumeSlider->OnValueChanged.AddDynamic(this, &UHawkeyeSettingsWidget::HandleSfxVolumeChanged);
		}
		if (AmbientVolumeSlider)
		{
			AmbientVolumeSlider->OnValueChanged.AddDynamic(this, &UHawkeyeSettingsWidget::HandleAmbientVolumeChanged);
		}
		if (SensitivitySlider)
		{
			SensitivitySlider->OnValueChanged.AddDynamic(this, &UHawkeyeSettingsWidget::HandleSensitivityChanged);
		}
		if (StickSensitivitySlider)
		{
			StickSensitivitySlider->OnValueChanged.AddDynamic(this, &UHawkeyeSettingsWidget::HandleStickSensitivityChanged);
		}
		if (InvertMouseYCheckBox)
		{
			InvertMouseYCheckBox->OnCheckStateChanged.AddDynamic(this, &UHawkeyeSettingsWidget::HandleInvertMouseYChanged);
		}
		if (InvertStickYCheckBox)
		{
			InvertStickYCheckBox->OnCheckStateChanged.AddDynamic(this, &UHawkeyeSettingsWidget::HandleInvertStickYChanged);
		}
		if (BackButton)
		{
			BackButton->OnClicked.AddDynamic(this, &UHawkeyeSettingsWidget::HandleBackClicked);
			BackButton->OnHovered.AddDynamic(this, &UHawkeyeSettingsWidget::HandleBackHovered);
		}
		bBound = true;
	}

	RefreshFromSettings();
}

void UHawkeyeSettingsWidget::NativeDestruct()
{
	if (bBound)
	{
		if (SensitivitySlider)
		{
			SensitivitySlider->OnValueChanged.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleSensitivityChanged);
		}
		if (StickSensitivitySlider)
		{
			StickSensitivitySlider->OnValueChanged.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleStickSensitivityChanged);
		}
		if (InvertMouseYCheckBox)
		{
			InvertMouseYCheckBox->OnCheckStateChanged.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleInvertMouseYChanged);
		}
		if (InvertStickYCheckBox)
		{
			InvertStickYCheckBox->OnCheckStateChanged.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleInvertStickYChanged);
		}
		if (MasterVolumeSlider)
		{
			MasterVolumeSlider->OnValueChanged.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleMasterVolumeChanged);
		}
		if (SfxVolumeSlider)
		{
			SfxVolumeSlider->OnValueChanged.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleSfxVolumeChanged);
		}
		if (AmbientVolumeSlider)
		{
			AmbientVolumeSlider->OnValueChanged.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleAmbientVolumeChanged);
		}
		if (BackButton)
		{
			BackButton->OnClicked.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleBackClicked);
			BackButton->OnHovered.RemoveDynamic(this, &UHawkeyeSettingsWidget::HandleBackHovered);
		}
		bBound = false;
	}

	Super::NativeDestruct();
}

void UHawkeyeSettingsWidget::RefreshFromSettings()
{
	const UHawkeyeSettingsSubsystem* SettingsSubsystem = UHawkeyeSettingsSubsystem::Get(this);
	const float Sensitivity = SettingsSubsystem
		? SettingsSubsystem->GetLookSensitivity()
		: FHawkeyeSettings().LookSensitivity;

	if (SensitivitySlider)
	{
		SensitivitySlider->SetValue(Sensitivity);
	}
	UpdateValueText(Sensitivity);

	const float StickSensitivity = SettingsSubsystem
		? SettingsSubsystem->GetStickSensitivity()
		: FHawkeyeSettings().StickSensitivity;

	if (StickSensitivitySlider)
	{
		StickSensitivitySlider->SetValue(StickSensitivity);
	}
	UpdateStickValueText(StickSensitivity);

	const bool bInvertMouseY = SettingsSubsystem
		? SettingsSubsystem->GetInvertMouseY()
		: FHawkeyeSettings().bInvertMouseY;
	if (InvertMouseYCheckBox)
	{
		InvertMouseYCheckBox->SetIsChecked(bInvertMouseY);
	}

	const bool bInvertStickY = SettingsSubsystem
		? SettingsSubsystem->GetInvertStickY()
		: FHawkeyeSettings().bInvertStickY;
	if (InvertStickYCheckBox)
	{
		InvertStickYCheckBox->SetIsChecked(bInvertStickY);
	}

	const FHawkeyeSettings Current = SettingsSubsystem ? SettingsSubsystem->GetSettings() : FHawkeyeSettings();
	const TTuple<USlider*, UTextBlock*, float> Volumes[] = {
		{ MasterVolumeSlider.Get(), MasterVolumeValueText.Get(), Current.MasterVolume },
		{ SfxVolumeSlider.Get(), SfxVolumeValueText.Get(), Current.SfxVolume },
		{ AmbientVolumeSlider.Get(), AmbientVolumeValueText.Get(), Current.AmbientVolume },
	};
	for (const TTuple<USlider*, UTextBlock*, float>& Volume : Volumes)
	{
		if (Volume.Get<0>())
		{
			Volume.Get<0>()->SetValue(Volume.Get<2>());
		}
		UpdateVolumeText(Volume.Get<1>(), Volume.Get<2>());
	}
}

void UHawkeyeSettingsWidget::UpdateVolumeText(UTextBlock* Text, float Value)
{
	if (Text)
	{
		Text->SetText(FText::FromString(FString::Printf(TEXT("%d%%"), FMath::RoundToInt(Value * 100.f))));
	}
}

void UHawkeyeSettingsWidget::HandleMasterVolumeChanged(float Value)
{
	UHawkeyeSettingsSubsystem* SettingsSubsystem = UHawkeyeSettingsSubsystem::Get(this);
	if (SettingsSubsystem)
	{
		SettingsSubsystem->SetMasterVolume(Value);
	}
	UpdateVolumeText(MasterVolumeValueText,
		SettingsSubsystem ? SettingsSubsystem->GetMasterVolume() : UHawkeyeSettingsSubsystem::ClampVolume(Value));
}

void UHawkeyeSettingsWidget::HandleSfxVolumeChanged(float Value)
{
	UHawkeyeSettingsSubsystem* SettingsSubsystem = UHawkeyeSettingsSubsystem::Get(this);
	if (SettingsSubsystem)
	{
		SettingsSubsystem->SetSfxVolume(Value);
	}
	UpdateVolumeText(SfxVolumeValueText,
		SettingsSubsystem ? SettingsSubsystem->GetSfxVolume() : UHawkeyeSettingsSubsystem::ClampVolume(Value));
}

void UHawkeyeSettingsWidget::HandleAmbientVolumeChanged(float Value)
{
	UHawkeyeSettingsSubsystem* SettingsSubsystem = UHawkeyeSettingsSubsystem::Get(this);
	if (SettingsSubsystem)
	{
		SettingsSubsystem->SetAmbientVolume(Value);
	}
	UpdateVolumeText(AmbientVolumeValueText,
		SettingsSubsystem ? SettingsSubsystem->GetAmbientVolume() : UHawkeyeSettingsSubsystem::ClampVolume(Value));
}

void UHawkeyeSettingsWidget::UpdateValueText(float Value)
{
	if (SensitivityValueText)
	{
		SensitivityValueText->SetText(FText::FromString(FString::Printf(TEXT("%.2f"), Value)));
	}
}

void UHawkeyeSettingsWidget::UpdateStickValueText(float Value)
{
	if (StickSensitivityValueText)
	{
		StickSensitivityValueText->SetText(FText::FromString(FString::Printf(TEXT("%.2f"), Value)));
	}
}

void UHawkeyeSettingsWidget::HandleSensitivityChanged(float Value)
{
	if (UHawkeyeSettingsSubsystem* SettingsSubsystem = UHawkeyeSettingsSubsystem::Get(this))
	{
		SettingsSubsystem->SetLookSensitivity(Value);
		UpdateValueText(SettingsSubsystem->GetLookSensitivity());
		return;
	}

	UpdateValueText(UHawkeyeSettingsSubsystem::ClampLookSensitivity(Value));
}

void UHawkeyeSettingsWidget::HandleStickSensitivityChanged(float Value)
{
	if (UHawkeyeSettingsSubsystem* SettingsSubsystem = UHawkeyeSettingsSubsystem::Get(this))
	{
		SettingsSubsystem->SetStickSensitivity(Value);
		UpdateStickValueText(SettingsSubsystem->GetStickSensitivity());
		return;
	}

	UpdateStickValueText(UHawkeyeSettingsSubsystem::ClampStickSensitivity(Value));
}

void UHawkeyeSettingsWidget::HandleInvertMouseYChanged(bool bIsChecked)
{
	if (UHawkeyeSettingsSubsystem* SettingsSubsystem = UHawkeyeSettingsSubsystem::Get(this))
	{
		SettingsSubsystem->SetInvertMouseY(bIsChecked);
	}
}

void UHawkeyeSettingsWidget::HandleInvertStickYChanged(bool bIsChecked)
{
	if (UHawkeyeSettingsSubsystem* SettingsSubsystem = UHawkeyeSettingsSubsystem::Get(this))
	{
		SettingsSubsystem->SetInvertStickY(bIsChecked);
	}
}

void UHawkeyeSettingsWidget::HandleBackClicked()
{
	UHawkeyeAudioSubsystem::PlayUI(this, EHawkeyeUISound::Click);
	OnBackRequested.Broadcast();
}

void UHawkeyeSettingsWidget::HandleBackHovered()
{
	UHawkeyeAudioSubsystem::PlayUI(this, EHawkeyeUISound::Hover);
}
